// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/luohao0308/luohao-blog/backend/internal/biz"
	"github.com/luohao0308/luohao-blog/backend/internal/conf"
	"github.com/luohao0308/luohao-blog/backend/internal/data"
	"github.com/luohao0308/luohao-blog/backend/internal/server"
	"github.com/luohao0308/luohao-blog/backend/internal/service"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, wechat *conf.Wechat, bootstrap *conf.Bootstrap, logger *slog.Logger) (*kratos.App, func(), error) {
	tokenIssuer, err := data.NewTokenIssuer(auth)
	if err != nil {
		return nil, nil, err
	}
	authorizer, err := data.NewAuthorizer()
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	universalClient := data.NewRedis(confData)
	articleRepo := data.NewArticleRepo(dataData, universalClient)
	articleSearchIndex, err := data.NewEsIndexer(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	articleUsecase := biz.NewArticleUsecase(articleRepo, articleSearchIndex)
	articleService := service.NewArticleService(articleUsecase)
	categoryRepo := data.NewCategoryRepo(dataData)
	categoryUsecase := biz.NewCategoryUsecase(categoryRepo)
	categoryService := service.NewCategoryService(categoryUsecase)
	userRepository := data.NewUserRepo(dataData)
	userUsecase := biz.NewUserUsecase(userRepository)
	sessionRepo := data.NewSessionRepo(universalClient)
	rateLimiter := data.NewRateLimiter(universalClient, auth)
	registerRateLimiter := data.NewRegisterRateLimiter(universalClient, auth)
	duration := data.NewRefreshTokenTTL(auth)
	authUsecase := biz.NewAuthUsecase(userUsecase, sessionRepo, tokenIssuer, rateLimiter, registerRateLimiter, duration)
	wechatClient := data.NewWechatClient(wechat)
	wechatBindingStore := data.NewWechatBindingStore(universalClient)
	wechatUsecase := biz.NewWechatUsecase(userUsecase, authUsecase, wechatClient, wechatBindingStore, rateLimiter)
	authService := service.NewAuthService(authUsecase, wechatUsecase)
	commentRepo := data.NewCommentRepo(dataData)
	commentRateLimiter := data.NewCommentRateLimiter(universalClient, auth)
	commentUsecase := biz.NewCommentUsecase(commentRepo, articleUsecase, userUsecase, commentRateLimiter)
	commentService := service.NewCommentService(commentUsecase)
	subscriberRepo := data.NewSubscriberRepo(dataData)
	subscribeRateLimiter := data.NewSubscribeRateLimiter(universalClient)
	subscriberUsecase := biz.NewSubscriberUsecase(subscriberRepo, subscribeRateLimiter)
	subscriberService := service.NewSubscriberService(subscriberUsecase)
	searchRateLimiter := data.NewSearchRateLimiter(universalClient, auth)
	articleSearchService := service.NewArticleSearchService(articleUsecase, searchRateLimiter)
	chatLLM := data.NewChatLLM(bootstrap)
	chatRateLimiter := data.NewChatRateLimiter(universalClient, auth)
	chatUsecase := biz.NewChatUsecase(articleUsecase, chatLLM, chatRateLimiter)
	chatService := service.NewChatService(chatUsecase)
	grpcServer := server.NewGRPCServer(confServer, tokenIssuer, authorizer, articleService, categoryService, authService, commentService, subscriberService, articleSearchService, chatService)
	avatarStore, err := data.NewAvatarStore(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	avatarUsecase := biz.NewAvatarUsecase(avatarStore, userUsecase)
	userService := service.NewUserService(userUsecase, avatarUsecase)
	httpServer, err := server.NewHTTPServer(confServer, tokenIssuer, authorizer, articleService, categoryService, authService, userService, commentService, subscriberService, articleSearchService, chatService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
