// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/luohao0308/luohao-blog/backend/internal/conf"
	"github.com/luohao0308/luohao-blog/backend/internal/server"
	"github.com/luohao0308/luohao-blog/backend/internal/service"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application. *conf.Data rejoins the graph in M1/S2
// together with the article repo.
func wireApp(confServer *conf.Server, logger *slog.Logger) (*kratos.App, func(), error) {
	articleService := service.NewArticleService()
	grpcServer := server.NewGRPCServer(confServer, articleService)
	httpServer := server.NewHTTPServer(confServer, articleService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
