// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Server *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data   *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Auth   *Auth                  `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	// Elasticsearch cluster for article full-text search. Absent disables
	// indexing and search endpoints return empty results.
	Es *Es `protobuf:"bytes,4,opt,name=es,proto3" json:"es,omitempty"`
	// OpenAI-compatible embedding service for semantic search vectors. Absent
	// or incomplete disables vector generation: the search index stays
	// BM25-only and everything else keeps working.
	Embedding *Embedding `protobuf:"bytes,5,opt,name=embedding,proto3" json:"embedding,omitempty"`
	// OpenAI-compatible chat LLM for retrieval-augmented answers (M4/S3).
	// Absent or incomplete disables the Chat RPC's generation side.
	Llm *Llm `protobuf:"bytes,6,opt,name=llm,proto3" json:"llm,omitempty"`
	// WeChat mini-program login (T-011/S2). Absent or incomplete disables the
	// wechat auth endpoints with FAILED_PRECONDITION.
	Wechat        *Wechat `protobuf:"bytes,7,opt,name=wechat,proto3" json:"wechat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Bootstrap) GetEs() *Es {
	if x != nil {
		return x.Es
	}
	return nil
}

func (x *Bootstrap) GetEmbedding() *Embedding {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *Bootstrap) GetLlm() *Llm {
	if x != nil {
		return x.Llm
	}
	return nil
}

func (x *Bootstrap) GetWechat() *Wechat {
	if x != nil {
		return x.Wechat
	}
	return nil
}

type Wechat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mini program AppID, e.g. wx58089476f518fd3f. Public by design.
	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// Mini program AppSecret from the mp.weixin.qq.com console. Provide it via
	// the git-ignored secrets file, never in source control.
	AppSecret     string `protobuf:"bytes,2,opt,name=app_secret,json=appSecret,proto3" json:"app_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wechat) Reset() {
	*x = Wechat{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wechat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wechat) ProtoMessage() {}

func (x *Wechat) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wechat.ProtoReflect.Descriptor instead.
func (*Wechat) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Wechat) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Wechat) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

type Llm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base URL of an OpenAI-compatible API, e.g. https://api.deepseek.com.
	// The client appends /chat/completions. Empty disables chat generation.
	BaseUrl string `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// API key sent as a bearer token. Provide it via environment or the
	// git-ignored secrets file, never in source control.
	ApiKey string `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// Chat model name, e.g. deepseek-chat.
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	// Per-request timeout. Defaults to 120s when unset: reasoning models can
	// legitimately think for a long time before the first token.
	Timeout *durationpb.Duration `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Optional reasoning effort sent as reasoning_effort (provider-specific
	// meaning; DeepSeek: none/low/high/max, default high). Set only when the
	// target provider supports it — DeepSeek defaults to minutes-long thinking,
	// so interactive chat wants "none" there.
	ReasoningEffort string `protobuf:"bytes,5,opt,name=reasoning_effort,json=reasoningEffort,proto3" json:"reasoning_effort,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Llm) Reset() {
	*x = Llm{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Llm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Llm) ProtoMessage() {}

func (x *Llm) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Llm.ProtoReflect.Descriptor instead.
func (*Llm) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Llm) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *Llm) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Llm) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Llm) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Llm) GetReasoningEffort() string {
	if x != nil {
		return x.ReasoningEffort
	}
	return ""
}

type Es struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node addresses, e.g. http://127.0.0.1:9200.
	Addresses []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// Index name for articles. Defaults to "articles".
	Index         string `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Es) Reset() {
	*x = Es{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Es) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Es) ProtoMessage() {}

func (x *Es) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Es.ProtoReflect.Descriptor instead.
func (*Es) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Es) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *Es) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

type Embedding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base URL of an OpenAI-compatible API, e.g. https://api.openai.com/v1.
	// The client appends /embeddings. Empty disables vector generation.
	BaseUrl string `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// API key sent as a bearer token. Provide it via environment, never in
	// source control.
	ApiKey string `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// Embedding model name, e.g. text-embedding-3-small.
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	// Vector dimension of the model output; sizes the ES dense_vector field.
	// Must match the model exactly. Required when base_url is set.
	Dimensions int32 `protobuf:"varint,4,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	// Per-request timeout. Defaults to 10s when unset.
	Timeout       *durationpb.Duration `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embedding) Reset() {
	*x = Embedding{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedding) ProtoMessage() {}

func (x *Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedding.ProtoReflect.Descriptor instead.
func (*Embedding) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Embedding) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *Embedding) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Embedding) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Embedding) GetDimensions() int32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *Embedding) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Database *Data_Database         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis    *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	// Directory for user-uploaded files (currently avatars). Created on boot
	// when missing. Defaults to ./data/uploads when unset; production mounts a
	// named Docker volume here so uploads survive container replacement.
	UploadsDir    string `protobuf:"bytes,3,opt,name=uploads_dir,json=uploadsDir,proto3" json:"uploads_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Data) GetUploadsDir() string {
	if x != nil {
		return x.UploadsDir
	}
	return ""
}

type Auth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Access token signing settings.
	Jwt *Auth_JWT `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	// Refresh session lifetime in Redis. Sliding: recreated on every refresh.
	// Defaults to 168h (7 days) when unset.
	RefreshTokenTtl *durationpb.Duration `protobuf:"bytes,2,opt,name=refresh_token_ttl,json=refreshTokenTtl,proto3" json:"refresh_token_ttl,omitempty"`
	// Login brute-force protection.
	RateLimit     *Auth_RateLimit `protobuf:"bytes,3,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *Auth) GetJwt() *Auth_JWT {
	if x != nil {
		return x.Jwt
	}
	return nil
}

func (x *Auth) GetRefreshTokenTtl() *durationpb.Duration {
	if x != nil {
		return x.RefreshTokenTtl
	}
	return nil
}

func (x *Auth) GetRateLimit() *Auth_RateLimit {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Database struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Driver name registered with database/sql, e.g. "mysql".
	Driver string `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	// Driver-specific DSN. Keep credentials out of version control.
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// Log every generated statement. Development only.
	Debug bool `protobuf:"varint,3,opt,name=debug,proto3" json:"debug,omitempty"`
	// Create or update tables from the ent schema on startup. Leave false in
	// production and apply migrations as a separate, reviewed step.
	AutoMigrate   bool `protobuf:"varint,4,opt,name=auto_migrate,json=autoMigrate,proto3" json:"auto_migrate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Data_Database) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *Data_Database) GetAutoMigrate() bool {
	if x != nil {
		return x.AutoMigrate
	}
	return false
}

type Data_Redis struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Network      string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr         string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	ReadTimeout  *durationpb.Duration   `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout *durationpb.Duration   `protobuf:"bytes,4,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	// AUTH password. Empty disables auth (local default); production injects
	// it via KRATOS_REDIS_PASSWORD so the requirepass'd Redis accepts us.
	Password      string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6, 1}
}

func (x *Data_Redis) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *Data_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Auth_JWT struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HMAC-SHA256 signing key for access tokens. Required: the server refuses
	// to start when empty. Provide it via environment, not source control.
	Secret string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	// Access token lifetime. Defaults to 15m when unset.
	AccessTokenTtl *durationpb.Duration `protobuf:"bytes,2,opt,name=access_token_ttl,json=accessTokenTtl,proto3" json:"access_token_ttl,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Auth_JWT) Reset() {
	*x = Auth_JWT{}
	mi := &file_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth_JWT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth_JWT) ProtoMessage() {}

func (x *Auth_JWT) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth_JWT.ProtoReflect.Descriptor instead.
func (*Auth_JWT) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{7, 0}
}

func (x *Auth_JWT) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Auth_JWT) GetAccessTokenTtl() *durationpb.Duration {
	if x != nil {
		return x.AccessTokenTtl
	}
	return nil
}

type Auth_RateLimit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Login attempts allowed per client IP inside login_window, for both
	// successful and failed logins. Defaults to 10 when unset.
	LoginAttempts int64 `protobuf:"varint,1,opt,name=login_attempts,json=loginAttempts,proto3" json:"login_attempts,omitempty"`
	// Fixed window size for the login counter. Defaults to 5m when unset.
	LoginWindow *durationpb.Duration `protobuf:"bytes,2,opt,name=login_window,json=loginWindow,proto3" json:"login_window,omitempty"`
	// Comment submissions allowed per client IP inside comment_window.
	// Defaults to 20 when unset.
	CommentAttempts int64 `protobuf:"varint,3,opt,name=comment_attempts,json=commentAttempts,proto3" json:"comment_attempts,omitempty"`
	// Fixed window size for the comment counter. Defaults to 5m when unset.
	CommentWindow *durationpb.Duration `protobuf:"bytes,4,opt,name=comment_window,json=commentWindow,proto3" json:"comment_window,omitempty"`
	// Chat questions allowed per client IP inside chat_window. Defaults to
	// 10 when unset.
	ChatAttempts int64 `protobuf:"varint,5,opt,name=chat_attempts,json=chatAttempts,proto3" json:"chat_attempts,omitempty"`
	// Fixed window size for the chat counter. Defaults to 5m when unset.
	ChatWindow *durationpb.Duration `protobuf:"bytes,6,opt,name=chat_window,json=chatWindow,proto3" json:"chat_window,omitempty"`
	// Public search queries allowed per client IP inside search_window.
	// Defaults to 60 when unset.
	SearchAttempts int64 `protobuf:"varint,9,opt,name=search_attempts,json=searchAttempts,proto3" json:"search_attempts,omitempty"`
	// Fixed window size for the search counter. Defaults to 1m when unset.
	SearchWindow *durationpb.Duration `protobuf:"bytes,10,opt,name=search_window,json=searchWindow,proto3" json:"search_window,omitempty"`
	// Account registrations allowed per client IP inside register_window.
	// Defaults to 10 when unset.
	RegisterAttempts int64 `protobuf:"varint,7,opt,name=register_attempts,json=registerAttempts,proto3" json:"register_attempts,omitempty"`
	// Fixed window size for the registration counter. Defaults to 5m when
	// unset.
	RegisterWindow *durationpb.Duration `protobuf:"bytes,8,opt,name=register_window,json=registerWindow,proto3" json:"register_window,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Auth_RateLimit) Reset() {
	*x = Auth_RateLimit{}
	mi := &file_conf_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth_RateLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth_RateLimit) ProtoMessage() {}

func (x *Auth_RateLimit) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth_RateLimit.ProtoReflect.Descriptor instead.
func (*Auth_RateLimit) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{7, 1}
}

func (x *Auth_RateLimit) GetLoginAttempts() int64 {
	if x != nil {
		return x.LoginAttempts
	}
	return 0
}

func (x *Auth_RateLimit) GetLoginWindow() *durationpb.Duration {
	if x != nil {
		return x.LoginWindow
	}
	return nil
}

func (x *Auth_RateLimit) GetCommentAttempts() int64 {
	if x != nil {
		return x.CommentAttempts
	}
	return 0
}

func (x *Auth_RateLimit) GetCommentWindow() *durationpb.Duration {
	if x != nil {
		return x.CommentWindow
	}
	return nil
}

func (x *Auth_RateLimit) GetChatAttempts() int64 {
	if x != nil {
		return x.ChatAttempts
	}
	return 0
}

func (x *Auth_RateLimit) GetChatWindow() *durationpb.Duration {
	if x != nil {
		return x.ChatWindow
	}
	return nil
}

func (x *Auth_RateLimit) GetSearchAttempts() int64 {
	if x != nil {
		return x.SearchAttempts
	}
	return 0
}

func (x *Auth_RateLimit) GetSearchWindow() *durationpb.Duration {
	if x != nil {
		return x.SearchWindow
	}
	return nil
}

func (x *Auth_RateLimit) GetRegisterAttempts() int64 {
	if x != nil {
		return x.RegisterAttempts
	}
	return 0
}

func (x *Auth_RateLimit) GetRegisterWindow() *durationpb.Duration {
	if x != nil {
		return x.RegisterWindow
	}
	return nil
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\xa7\x02\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x12$\n" +
	"\x04auth\x18\x03 \x01(\v2\x10.kratos.api.AuthR\x04auth\x12\x1e\n" +
	"\x02es\x18\x04 \x01(\v2\x0e.kratos.api.EsR\x02es\x123\n" +
	"\tembedding\x18\x05 \x01(\v2\x15.kratos.api.EmbeddingR\tembedding\x12!\n" +
	"\x03llm\x18\x06 \x01(\v2\x0f.kratos.api.LlmR\x03llm\x12*\n" +
	"\x06wechat\x18\a \x01(\v2\x12.kratos.api.WechatR\x06wechat\">\n" +
	"\x06Wechat\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"app_secret\x18\x02 \x01(\tR\tappSecret\"\xaf\x01\n" +
	"\x03Llm\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12)\n" +
	"\x10reasoning_effort\x18\x05 \x01(\tR\x0freasoningEffort\"8\n" +
	"\x02Es\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\x12\x14\n" +
	"\x05index\x18\x02 \x01(\tR\x05index\"\xaa\x01\n" +
	"\tEmbedding\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x04 \x01(\x05R\n" +
	"dimensions\x123\n" +
	"\atimeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xb8\x02\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xd3\x03\n" +
	"\x04Data\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.kratos.api.Data.DatabaseR\bdatabase\x12,\n" +
	"\x05redis\x18\x02 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x12\x1f\n" +
	"\vuploads_dir\x18\x03 \x01(\tR\n" +
	"uploadsDir\x1as\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05debug\x18\x03 \x01(\bR\x05debug\x12!\n" +
	"\fauto_migrate\x18\x04 \x01(\bR\vautoMigrate\x1a\xcf\x01\n" +
	"\x05Redis\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12<\n" +
	"\fread_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\"\xaf\x06\n" +
	"\x04Auth\x12&\n" +
	"\x03jwt\x18\x01 \x01(\v2\x14.kratos.api.Auth.JWTR\x03jwt\x12E\n" +
	"\x11refresh_token_ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0frefreshTokenTtl\x129\n" +
	"\n" +
	"rate_limit\x18\x03 \x01(\v2\x1a.kratos.api.Auth.RateLimitR\trateLimit\x1ab\n" +
	"\x03JWT\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12C\n" +
	"\x10access_token_ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0eaccessTokenTtl\x1a\x98\x04\n" +
	"\tRateLimit\x12%\n" +
	"\x0elogin_attempts\x18\x01 \x01(\x03R\rloginAttempts\x12<\n" +
	"\flogin_window\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\vloginWindow\x12)\n" +
	"\x10comment_attempts\x18\x03 \x01(\x03R\x0fcommentAttempts\x12@\n" +
	"\x0ecomment_window\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\rcommentWindow\x12#\n" +
	"\rchat_attempts\x18\x05 \x01(\x03R\fchatAttempts\x12:\n" +
	"\vchat_window\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"chatWindow\x12'\n" +
	"\x0fsearch_attempts\x18\t \x01(\x03R\x0esearchAttempts\x12>\n" +
	"\rsearch_window\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\fsearchWindow\x12+\n" +
	"\x11register_attempts\x18\a \x01(\x03R\x10registerAttempts\x12B\n" +
	"\x0fregister_window\x18\b \x01(\v2\x19.google.protobuf.DurationR\x0eregisterWindowB7Z5github.com/go-kratos/kratos-layout/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: kratos.api.Bootstrap
	(*Wechat)(nil),              // 1: kratos.api.Wechat
	(*Llm)(nil),                 // 2: kratos.api.Llm
	(*Es)(nil),                  // 3: kratos.api.Es
	(*Embedding)(nil),           // 4: kratos.api.Embedding
	(*Server)(nil),              // 5: kratos.api.Server
	(*Data)(nil),                // 6: kratos.api.Data
	(*Auth)(nil),                // 7: kratos.api.Auth
	(*Server_HTTP)(nil),         // 8: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),         // 9: kratos.api.Server.GRPC
	(*Data_Database)(nil),       // 10: kratos.api.Data.Database
	(*Data_Redis)(nil),          // 11: kratos.api.Data.Redis
	(*Auth_JWT)(nil),            // 12: kratos.api.Auth.JWT
	(*Auth_RateLimit)(nil),      // 13: kratos.api.Auth.RateLimit
	(*durationpb.Duration)(nil), // 14: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	5,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	6,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	7,  // 2: kratos.api.Bootstrap.auth:type_name -> kratos.api.Auth
	3,  // 3: kratos.api.Bootstrap.es:type_name -> kratos.api.Es
	4,  // 4: kratos.api.Bootstrap.embedding:type_name -> kratos.api.Embedding
	2,  // 5: kratos.api.Bootstrap.llm:type_name -> kratos.api.Llm
	1,  // 6: kratos.api.Bootstrap.wechat:type_name -> kratos.api.Wechat
	14, // 7: kratos.api.Llm.timeout:type_name -> google.protobuf.Duration
	14, // 8: kratos.api.Embedding.timeout:type_name -> google.protobuf.Duration
	8,  // 9: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	9,  // 10: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	10, // 11: kratos.api.Data.database:type_name -> kratos.api.Data.Database
	11, // 12: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	12, // 13: kratos.api.Auth.jwt:type_name -> kratos.api.Auth.JWT
	14, // 14: kratos.api.Auth.refresh_token_ttl:type_name -> google.protobuf.Duration
	13, // 15: kratos.api.Auth.rate_limit:type_name -> kratos.api.Auth.RateLimit
	14, // 16: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	14, // 17: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	14, // 18: kratos.api.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	14, // 19: kratos.api.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	14, // 20: kratos.api.Auth.JWT.access_token_ttl:type_name -> google.protobuf.Duration
	14, // 21: kratos.api.Auth.RateLimit.login_window:type_name -> google.protobuf.Duration
	14, // 22: kratos.api.Auth.RateLimit.comment_window:type_name -> google.protobuf.Duration
	14, // 23: kratos.api.Auth.RateLimit.chat_window:type_name -> google.protobuf.Duration
	14, // 24: kratos.api.Auth.RateLimit.search_window:type_name -> google.protobuf.Duration
	14, // 25: kratos.api.Auth.RateLimit.register_window:type_name -> google.protobuf.Duration
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
