// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: blog/v1/article.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ArticleStatus is the lifecycle state of an article.
type ArticleStatus int32

const (
	// Default value. Never returned by the server.
	ArticleStatus_ARTICLE_STATUS_UNSPECIFIED ArticleStatus = 0
	// The article is being written; it does not appear in public reads.
	ArticleStatus_ARTICLE_STATUS_DRAFT ArticleStatus = 1
	// The article is published and appears in public reads.
	ArticleStatus_ARTICLE_STATUS_PUBLISHED ArticleStatus = 2
	// The article is soft-deleted: the record is retained by the server but no
	// longer appears in GetArticle or ListArticles results.
	ArticleStatus_ARTICLE_STATUS_DELETED ArticleStatus = 3
)

// Enum value maps for ArticleStatus.
var (
	ArticleStatus_name = map[int32]string{
		0: "ARTICLE_STATUS_UNSPECIFIED",
		1: "ARTICLE_STATUS_DRAFT",
		2: "ARTICLE_STATUS_PUBLISHED",
		3: "ARTICLE_STATUS_DELETED",
	}
	ArticleStatus_value = map[string]int32{
		"ARTICLE_STATUS_UNSPECIFIED": 0,
		"ARTICLE_STATUS_DRAFT":       1,
		"ARTICLE_STATUS_PUBLISHED":   2,
		"ARTICLE_STATUS_DELETED":     3,
	}
)

func (x ArticleStatus) Enum() *ArticleStatus {
	p := new(ArticleStatus)
	*p = x
	return p
}

func (x ArticleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArticleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_blog_v1_article_proto_enumTypes[0].Descriptor()
}

func (ArticleStatus) Type() protoreflect.EnumType {
	return &file_blog_v1_article_proto_enumTypes[0]
}

func (x ArticleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArticleStatus.Descriptor instead.
func (ArticleStatus) EnumDescriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{0}
}

// Article is the canonical representation of a blog article.
type Article struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application-generated UUIDv7 identifier. Read-only on create.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Unique URL-safe identifier in [a-z0-9-]. Immutable after creation.
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	// Human-readable title.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// Optional short excerpt used in list views; derived from content_md when
	// empty.
	Summary string `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	// Markdown source of the article body.
	ContentMd string `protobuf:"bytes,5,opt,name=content_md,json=contentMd,proto3" json:"content_md,omitempty"`
	// Server-rendered HTML for content_md. Read-only: regenerated whenever
	// content_md changes.
	ContentHtml string `protobuf:"bytes,6,opt,name=content_html,json=contentHtml,proto3" json:"content_html,omitempty"`
	// Tag names attached to the article. Tags are created on first use.
	Tags []string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	// Lifecycle state. Server-assigned: new articles start as DRAFT; move them
	// with UpdateArticle on status; DeleteArticle moves them to DELETED.
	Status ArticleStatus `protobuf:"varint,8,opt,name=status,proto3,enum=blog.v1.ArticleStatus" json:"status,omitempty"`
	// Time at which the article first moved to PUBLISHED. Server-assigned.
	PublishedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	// Time at which the article was created. Server-assigned, read-only.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Time at which the article was last modified. Server-assigned, read-only.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Public read counter. Incremented when a client reports a view through
	// MarkArticleViewed and the 24h per-client dedup window admits it.
	ViewCount uint64 `protobuf:"varint,12,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	// Public like counter. Incremented when a client reports a like through
	// MarkArticleLiked and the 24h per-client dedup window admits it.
	LikeCount uint64 `protobuf:"varint,14,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	// Single curated category of the article. Server-managed through
	// Create/UpdateArticle on the category field; absent when uncategorized.
	Category      *CategoryBrief `protobuf:"bytes,13,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_blog_v1_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Article) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Article) GetContentMd() string {
	if x != nil {
		return x.ContentMd
	}
	return ""
}

func (x *Article) GetContentHtml() string {
	if x != nil {
		return x.ContentHtml
	}
	return ""
}

func (x *Article) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Article) GetStatus() ArticleStatus {
	if x != nil {
		return x.Status
	}
	return ArticleStatus_ARTICLE_STATUS_UNSPECIFIED
}

func (x *Article) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *Article) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Article) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Article) GetViewCount() uint64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Article) GetLikeCount() uint64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Article) GetCategory() *CategoryBrief {
	if x != nil {
		return x.Category
	}
	return nil
}

// CategoryBrief is the category summary attached to an article response.
type CategoryBrief struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique slug of the category; the public identifier used in filters and
	// category routes.
	Slug string `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	// Display name of the category.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryBrief) Reset() {
	*x = CategoryBrief{}
	mi := &file_blog_v1_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryBrief) ProtoMessage() {}

func (x *CategoryBrief) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryBrief.ProtoReflect.Descriptor instead.
func (*CategoryBrief) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{1}
}

func (x *CategoryBrief) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CategoryBrief) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ArticleSet is a paginated collection of articles returned by ListArticles.
type ArticleSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The page of articles in the order requested by ListArticlesRequest.order_by.
	Articles []*Article `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	// Token used to retrieve the next page via ListArticlesRequest.page_token.
	// Empty when there are no more results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleSet) Reset() {
	*x = ArticleSet{}
	mi := &file_blog_v1_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleSet) ProtoMessage() {}

func (x *ArticleSet) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleSet.ProtoReflect.Descriptor instead.
func (*ArticleSet) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{2}
}

func (x *ArticleSet) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *ArticleSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// CreateArticleRequest is the input for ArticleService.CreateArticle.
type CreateArticleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The article to create. The id, content_html, status, published_at,
	// created_at, and updated_at fields are ignored on input and populated by
	// the server in the response. New articles are created as DRAFT.
	Article       *Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	mi := &file_blog_v1_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{3}
}

func (x *CreateArticleRequest) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

// GetArticleRequest is the input for ArticleService.GetArticle.
type GetArticleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique slug of the article to retrieve.
	Slug          string `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_blog_v1_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{4}
}

func (x *GetArticleRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

// ListArticlesRequest is the input for ArticleService.ListArticles.
type ListArticlesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Maximum number of articles to return in a single page.
	// The server may apply a default and a maximum when unset or out of range.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. Token from a previous response's next_page_token used to fetch
	// the next page. Leave empty to request the first page.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. The standard list filter.
	// Supported fields:
	//   - `slug` (i.e. `slug:"m0-scaffold"`)
	//   - `title` (i.e. `title:"kratos"`)
	//   - `status` (i.e. `status:"PUBLISHED"`)
	//   - `tag` (i.e. `tag:"go"`)
	//   - `category` (i.e. `category:"engineering"`)
	//   - `published_at` range (i.e. `published_at>="2026-01-01T00:00:00Z"`)
	//   - `created_at` range, `updated_at` range
	Filter string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional. A comma-separated list of fields to order by.
	// Supported fields:
	//   - `slug`
	//   - `title`
	//   - `published_at`
	//   - `created_at`
	//   - `updated_at`
	//
	// Append ` desc` to a field for descending order, e.g. `published_at desc`.
	// Defaults to ascending order when no direction is supplied.
	OrderBy       string `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesRequest) Reset() {
	*x = ListArticlesRequest{}
	mi := &file_blog_v1_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesRequest) ProtoMessage() {}

func (x *ListArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesRequest.ProtoReflect.Descriptor instead.
func (*ListArticlesRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{5}
}

func (x *ListArticlesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListArticlesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListArticlesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListArticlesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

// UpdateArticleRequest is the input for ArticleService.UpdateArticle.
type UpdateArticleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The article carrying the new field values. article.slug identifies the
	// target record and must be set.
	Article *Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	// Set of field paths in article to overwrite. Fields not listed are left
	// unchanged. Use a single path of `*` to replace every mutable field.
	// The `category` path takes a CategoryBrief whose slug must reference an
	// existing category, or an empty CategoryBrief to make the article
	// uncategorized.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleRequest) Reset() {
	*x = UpdateArticleRequest{}
	mi := &file_blog_v1_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest) ProtoMessage() {}

func (x *UpdateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateArticleRequest) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *UpdateArticleRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// DeleteArticleRequest is the input for ArticleService.DeleteArticle.
type DeleteArticleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique slug of the article to delete.
	Slug          string `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_blog_v1_article_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteArticleRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

// MarkArticleViewedRequest is the input for ArticleService.MarkArticleViewed.
// The client identity comes from the transport (client IP), not from the
// message body.
type MarkArticleViewedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique slug of the article being viewed.
	Slug          string `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkArticleViewedRequest) Reset() {
	*x = MarkArticleViewedRequest{}
	mi := &file_blog_v1_article_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkArticleViewedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkArticleViewedRequest) ProtoMessage() {}

func (x *MarkArticleViewedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkArticleViewedRequest.ProtoReflect.Descriptor instead.
func (*MarkArticleViewedRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{8}
}

func (x *MarkArticleViewedRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

// MarkArticleLikedRequest is the input for ArticleService.MarkArticleLiked.
// The client identity comes from the transport (client IP), not from the
// message body.
type MarkArticleLikedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique slug of the article being liked.
	Slug          string `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkArticleLikedRequest) Reset() {
	*x = MarkArticleLikedRequest{}
	mi := &file_blog_v1_article_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkArticleLikedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkArticleLikedRequest) ProtoMessage() {}

func (x *MarkArticleLikedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkArticleLikedRequest.ProtoReflect.Descriptor instead.
func (*MarkArticleLikedRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{9}
}

func (x *MarkArticleLikedRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

var File_blog_v1_article_proto protoreflect.FileDescriptor

const file_blog_v1_article_proto_rawDesc = "" +
	"\n" +
	"\x15blog/v1/article.proto\x12\ablog.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x04\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04slug\x18\x02 \x01(\tB\x03\xe0A\x02R\x04slug\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tB\x03\xe0A\x02R\x05title\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\"\n" +
	"\n" +
	"content_md\x18\x05 \x01(\tB\x03\xe0A\x02R\tcontentMd\x12!\n" +
	"\fcontent_html\x18\x06 \x01(\tR\vcontentHtml\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12.\n" +
	"\x06status\x18\b \x01(\x0e2\x16.blog.v1.ArticleStatusR\x06status\x12=\n" +
	"\fpublished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"view_count\x18\f \x01(\x04R\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\x0e \x01(\x04R\tlikeCount\x122\n" +
	"\bcategory\x18\r \x01(\v2\x16.blog.v1.CategoryBriefR\bcategory\"7\n" +
	"\rCategoryBrief\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"b\n" +
	"\n" +
	"ArticleSet\x12,\n" +
	"\barticles\x18\x01 \x03(\v2\x10.blog.v1.ArticleR\barticles\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"G\n" +
	"\x14CreateArticleRequest\x12/\n" +
	"\aarticle\x18\x01 \x01(\v2\x10.blog.v1.ArticleB\x03\xe0A\x02R\aarticle\",\n" +
	"\x11GetArticleRequest\x12\x17\n" +
	"\x04slug\x18\x01 \x01(\tB\x03\xe0A\x02R\x04slug\"\x84\x01\n" +
	"\x13ListArticlesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"\x89\x01\n" +
	"\x14UpdateArticleRequest\x12/\n" +
	"\aarticle\x18\x01 \x01(\v2\x10.blog.v1.ArticleB\x03\xe0A\x02R\aarticle\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02R\n" +
	"updateMask\"/\n" +
	"\x14DeleteArticleRequest\x12\x17\n" +
	"\x04slug\x18\x01 \x01(\tB\x03\xe0A\x02R\x04slug\"3\n" +
	"\x18MarkArticleViewedRequest\x12\x17\n" +
	"\x04slug\x18\x01 \x01(\tB\x03\xe0A\x02R\x04slug\"2\n" +
	"\x17MarkArticleLikedRequest\x12\x17\n" +
	"\x04slug\x18\x01 \x01(\tB\x03\xe0A\x02R\x04slug*\x83\x01\n" +
	"\rArticleStatus\x12\x1e\n" +
	"\x1aARTICLE_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ARTICLE_STATUS_DRAFT\x10\x01\x12\x1c\n" +
	"\x18ARTICLE_STATUS_PUBLISHED\x10\x02\x12\x1a\n" +
	"\x16ARTICLE_STATUS_DELETED\x10\x032\xe4\x05\n" +
	"\x0eArticleService\x12f\n" +
	"\rCreateArticle\x12\x1d.blog.v1.CreateArticleRequest\x1a\x10.blog.v1.Article\"$\x82\xd3\xe4\x93\x02\x1e:\aarticle\"\x13/v1/articles/create\x12\\\n" +
	"\fListArticles\x12\x1c.blog.v1.ListArticlesRequest\x1a\x13.blog.v1.ArticleSet\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/articles/list\x12W\n" +
	"\n" +
	"GetArticle\x12\x1a.blog.v1.GetArticleRequest\x1a\x10.blog.v1.Article\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/articles/{slug}\x12f\n" +
	"\rUpdateArticle\x12\x1d.blog.v1.UpdateArticleRequest\x1a\x10.blog.v1.Article\"$\x82\xd3\xe4\x93\x02\x1e:\aarticle\x1a\x13/v1/articles/update\x12c\n" +
	"\rDeleteArticle\x12\x1d.blog.v1.DeleteArticleRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v1/articles/{slug}\x12s\n" +
	"\x11MarkArticleViewed\x12!.blog.v1.MarkArticleViewedRequest\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/articles/{slug}/view\x12q\n" +
	"\x10MarkArticleLiked\x12 .blog.v1.MarkArticleLikedRequest\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/articles/{slug}/likeBd\n" +
	"\x18io.grpc.examples.blog.v1B\fArticleProtoP\x01Z8github.com/luohao0308/luohao-blog/backend/api/blog/v1;v1b\x06proto3"

var (
	file_blog_v1_article_proto_rawDescOnce sync.Once
	file_blog_v1_article_proto_rawDescData []byte
)

func file_blog_v1_article_proto_rawDescGZIP() []byte {
	file_blog_v1_article_proto_rawDescOnce.Do(func() {
		file_blog_v1_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_v1_article_proto_rawDesc), len(file_blog_v1_article_proto_rawDesc)))
	})
	return file_blog_v1_article_proto_rawDescData
}

var file_blog_v1_article_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blog_v1_article_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_blog_v1_article_proto_goTypes = []any{
	(ArticleStatus)(0),               // 0: blog.v1.ArticleStatus
	(*Article)(nil),                  // 1: blog.v1.Article
	(*CategoryBrief)(nil),            // 2: blog.v1.CategoryBrief
	(*ArticleSet)(nil),               // 3: blog.v1.ArticleSet
	(*CreateArticleRequest)(nil),     // 4: blog.v1.CreateArticleRequest
	(*GetArticleRequest)(nil),        // 5: blog.v1.GetArticleRequest
	(*ListArticlesRequest)(nil),      // 6: blog.v1.ListArticlesRequest
	(*UpdateArticleRequest)(nil),     // 7: blog.v1.UpdateArticleRequest
	(*DeleteArticleRequest)(nil),     // 8: blog.v1.DeleteArticleRequest
	(*MarkArticleViewedRequest)(nil), // 9: blog.v1.MarkArticleViewedRequest
	(*MarkArticleLikedRequest)(nil),  // 10: blog.v1.MarkArticleLikedRequest
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),    // 12: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),            // 13: google.protobuf.Empty
}
var file_blog_v1_article_proto_depIdxs = []int32{
	0,  // 0: blog.v1.Article.status:type_name -> blog.v1.ArticleStatus
	11, // 1: blog.v1.Article.published_at:type_name -> google.protobuf.Timestamp
	11, // 2: blog.v1.Article.created_at:type_name -> google.protobuf.Timestamp
	11, // 3: blog.v1.Article.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 4: blog.v1.Article.category:type_name -> blog.v1.CategoryBrief
	1,  // 5: blog.v1.ArticleSet.articles:type_name -> blog.v1.Article
	1,  // 6: blog.v1.CreateArticleRequest.article:type_name -> blog.v1.Article
	1,  // 7: blog.v1.UpdateArticleRequest.article:type_name -> blog.v1.Article
	12, // 8: blog.v1.UpdateArticleRequest.update_mask:type_name -> google.protobuf.FieldMask
	4,  // 9: blog.v1.ArticleService.CreateArticle:input_type -> blog.v1.CreateArticleRequest
	6,  // 10: blog.v1.ArticleService.ListArticles:input_type -> blog.v1.ListArticlesRequest
	5,  // 11: blog.v1.ArticleService.GetArticle:input_type -> blog.v1.GetArticleRequest
	7,  // 12: blog.v1.ArticleService.UpdateArticle:input_type -> blog.v1.UpdateArticleRequest
	8,  // 13: blog.v1.ArticleService.DeleteArticle:input_type -> blog.v1.DeleteArticleRequest
	9,  // 14: blog.v1.ArticleService.MarkArticleViewed:input_type -> blog.v1.MarkArticleViewedRequest
	10, // 15: blog.v1.ArticleService.MarkArticleLiked:input_type -> blog.v1.MarkArticleLikedRequest
	1,  // 16: blog.v1.ArticleService.CreateArticle:output_type -> blog.v1.Article
	3,  // 17: blog.v1.ArticleService.ListArticles:output_type -> blog.v1.ArticleSet
	1,  // 18: blog.v1.ArticleService.GetArticle:output_type -> blog.v1.Article
	1,  // 19: blog.v1.ArticleService.UpdateArticle:output_type -> blog.v1.Article
	13, // 20: blog.v1.ArticleService.DeleteArticle:output_type -> google.protobuf.Empty
	13, // 21: blog.v1.ArticleService.MarkArticleViewed:output_type -> google.protobuf.Empty
	13, // 22: blog.v1.ArticleService.MarkArticleLiked:output_type -> google.protobuf.Empty
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_blog_v1_article_proto_init() }
func file_blog_v1_article_proto_init() {
	if File_blog_v1_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_v1_article_proto_rawDesc), len(file_blog_v1_article_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_v1_article_proto_goTypes,
		DependencyIndexes: file_blog_v1_article_proto_depIdxs,
		EnumInfos:         file_blog_v1_article_proto_enumTypes,
		MessageInfos:      file_blog_v1_article_proto_msgTypes,
	}.Build()
	File_blog_v1_article_proto = out.File
	file_blog_v1_article_proto_goTypes = nil
	file_blog_v1_article_proto_depIdxs = nil
}
