// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: blog/v1/auth.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_Register_FullMethodName       = "/blog.v1.AuthService/Register"
	AuthService_Login_FullMethodName          = "/blog.v1.AuthService/Login"
	AuthService_Refresh_FullMethodName        = "/blog.v1.AuthService/Refresh"
	AuthService_Logout_FullMethodName         = "/blog.v1.AuthService/Logout"
	AuthService_GetMe_FullMethodName          = "/blog.v1.AuthService/GetMe"
	AuthService_UpdatePassword_FullMethodName = "/blog.v1.AuthService/UpdatePassword"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthService issues and revokes the credentials used to call privileged
// endpoints. Registration is open: anyone can create a READER account with an
// email, a password, and a display name (no email verification yet; abuse is
// bounded by per-IP rate limiting and comment pre-moderation). ADMIN accounts
// are still created only by the seed command. The access
// token is a short-lived JWT carried in the
// Authorization header; the refresh token is an opaque secret delivered as an
// httpOnly cookie (Path=/v1/auth) and rotated on every refresh, with the
// server-side session kept in Redis. Refresh and Logout read the token from
// the cookie, falling back to the X-Refresh-Token header for non-cookie
// clients.
type AuthServiceClient interface {
	// Register creates a READER account and signs the caller in: the reply is
	// the same token pair Login returns, delivered with the refresh cookie.
	// Returns INVALID_ARGUMENT when fields fail validation and CONFLICT when
	// the email is already registered. Rate limited per client IP; excess
	// attempts return TOO_MANY_REQUESTS.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*LoginReply, error)
	// Login verifies credentials and returns an access token, a refresh token
	// cookie, and the account. Returns INVALID_ARGUMENT when fields are empty
	// and UNAUTHORIZED when the credentials are wrong (indistinguishable
	// between unknown email and wrong password). Rate limited per client IP;
	// excess attempts return TOO_MANY_REQUESTS.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	// Refresh rotates the refresh session and returns a new access token and a
	// replacement refresh cookie. Each refresh token is single-use: replaying a
	// rotated one is rejected with UNAUTHORIZED. Returns UNAUTHORIZED when the
	// cookie (or header) is missing, expired, revoked, or belongs to a deleted
	// account.
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*LoginReply, error)
	// Logout revokes the refresh session and clears the refresh cookie. The
	// operation is idempotent: logout without a valid session still clears the
	// cookie and succeeds. The just-issued access token remains valid until it
	// expires (at most access_token_ttl).
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetMe returns the account identified by the access token in the
	// Authorization header. Returns UNAUTHORIZED when the token is missing,
	// malformed, forged, or expired.
	GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*User, error)
	// UpdatePassword rotates the calling account's password. The current
	// password must be supplied and is verified before the change; the new
	// password follows the same rules as account creation (at least 8
	// characters). Existing refresh sessions keep working until their natural
	// expiry; the next login must use the new password.
	// Authorization: any authenticated account (Authorization: Bearer).
	// Returns UNAUTHORIZED when the old password is wrong, INVALID_ARGUMENT
	// when fields are empty or the new password is too short.
	UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, AuthService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, AuthService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, AuthService_Refresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, AuthService_GetMe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthService_UpdatePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// AuthService issues and revokes the credentials used to call privileged
// endpoints. Registration is open: anyone can create a READER account with an
// email, a password, and a display name (no email verification yet; abuse is
// bounded by per-IP rate limiting and comment pre-moderation). ADMIN accounts
// are still created only by the seed command. The access
// token is a short-lived JWT carried in the
// Authorization header; the refresh token is an opaque secret delivered as an
// httpOnly cookie (Path=/v1/auth) and rotated on every refresh, with the
// server-side session kept in Redis. Refresh and Logout read the token from
// the cookie, falling back to the X-Refresh-Token header for non-cookie
// clients.
type AuthServiceServer interface {
	// Register creates a READER account and signs the caller in: the reply is
	// the same token pair Login returns, delivered with the refresh cookie.
	// Returns INVALID_ARGUMENT when fields fail validation and CONFLICT when
	// the email is already registered. Rate limited per client IP; excess
	// attempts return TOO_MANY_REQUESTS.
	Register(context.Context, *RegisterRequest) (*LoginReply, error)
	// Login verifies credentials and returns an access token, a refresh token
	// cookie, and the account. Returns INVALID_ARGUMENT when fields are empty
	// and UNAUTHORIZED when the credentials are wrong (indistinguishable
	// between unknown email and wrong password). Rate limited per client IP;
	// excess attempts return TOO_MANY_REQUESTS.
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	// Refresh rotates the refresh session and returns a new access token and a
	// replacement refresh cookie. Each refresh token is single-use: replaying a
	// rotated one is rejected with UNAUTHORIZED. Returns UNAUTHORIZED when the
	// cookie (or header) is missing, expired, revoked, or belongs to a deleted
	// account.
	Refresh(context.Context, *RefreshRequest) (*LoginReply, error)
	// Logout revokes the refresh session and clears the refresh cookie. The
	// operation is idempotent: logout without a valid session still clears the
	// cookie and succeeds. The just-issued access token remains valid until it
	// expires (at most access_token_ttl).
	Logout(context.Context, *LogoutRequest) (*emptypb.Empty, error)
	// GetMe returns the account identified by the access token in the
	// Authorization header. Returns UNAUTHORIZED when the token is missing,
	// malformed, forged, or expired.
	GetMe(context.Context, *GetMeRequest) (*User, error)
	// UpdatePassword rotates the calling account's password. The current
	// password must be supplied and is verified before the change; the new
	// password follows the same rules as account creation (at least 8
	// characters). Existing refresh sessions keep working until their natural
	// expiry; the next login must use the new password.
	// Authorization: any authenticated account (Authorization: Bearer).
	// Returns UNAUTHORIZED when the old password is wrong, INVALID_ARGUMENT
	// when fields are empty or the new password is too short.
	UpdatePassword(context.Context, *UpdatePasswordRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) Register(context.Context, *RegisterRequest) (*LoginReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAuthServiceServer) Login(context.Context, *LoginRequest) (*LoginReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServiceServer) Refresh(context.Context, *RefreshRequest) (*LoginReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedAuthServiceServer) Logout(context.Context, *LogoutRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAuthServiceServer) GetMe(context.Context, *GetMeRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMe not implemented")
}
func (UnimplementedAuthServiceServer) UpdatePassword(context.Context, *UpdatePasswordRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePassword not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Refresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetMe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetMe(ctx, req.(*GetMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_UpdatePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdatePassword(ctx, req.(*UpdatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blog.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AuthService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _AuthService_Refresh_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AuthService_Logout_Handler,
		},
		{
			MethodName: "GetMe",
			Handler:    _AuthService_GetMe_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _AuthService_UpdatePassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog/v1/auth.proto",
}
