// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: blog/v1/auth.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserRole is the account role. Values mirror the domain model; ADMIN can
// author and manage articles, READER is a self-registered reader account
// that can comment and manage its own profile.
type UserRole int32

const (
	// Default value. Never returned by the server.
	UserRole_USER_ROLE_UNSPECIFIED UserRole = 0
	// Can author and manage articles.
	UserRole_USER_ROLE_ADMIN UserRole = 1
	// Self-registered reader; comments and manages its own profile.
	UserRole_USER_ROLE_READER UserRole = 2
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_UNSPECIFIED",
		1: "USER_ROLE_ADMIN",
		2: "USER_ROLE_READER",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_UNSPECIFIED": 0,
		"USER_ROLE_ADMIN":       1,
		"USER_ROLE_READER":      2,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_blog_v1_auth_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_blog_v1_auth_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_blog_v1_auth_proto_rawDescGZIP(), []int{0}
}

// WechatLoginStatus tells the mini program which follow-up to take.
type WechatLoginStatus int32

const (
	// Default value. Never returned by the server.
	WechatLoginStatus_WECHAT_LOGIN_STATUS_UNSPECIFIED WechatLoginStatus = 0
	// The openid was already bound: `login` carries the token pair.
	WechatLoginStatus_WECHAT_LOGIN_STATUS_OK WechatLoginStatus = 1
	// The openid is new: `binding_ticket` is set and the client must call
	// BindWechat with the account's email and password.
	WechatLoginStatus_WECHAT_LOGIN_STATUS_BINDING_REQUIRED WechatLoginStatus = 2
)

// Enum value maps for WechatLoginStatus.
var (
	WechatLoginStatus_name = map[int32]string{
		0: "WECHAT_LOGIN_STATUS_UNSPECIFIED",
		1: "WECHAT_LOGIN_STATUS_OK",
		2: "WECHAT_LOGIN_STATUS_BINDING_REQUIRED",
	}
	WechatLoginStatus_value = map[string]int32{
		"WECHAT_LOGIN_STATUS_UNSPECIFIED":      0,
		"WECHAT_LOGIN_STATUS_OK":               1,
		"WECHAT_LOGIN_STATUS_BINDING_REQUIRED": 2,
	}
)

func (x WechatLoginStatus) Enum() *WechatLoginStatus {
	p := new(WechatLoginStatus)
	*p = x
	return p
}

func (x WechatLoginStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WechatLoginStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_blog_v1_auth_proto_enumTypes[1].Descriptor()
}

func (WechatLoginStatus) Type() protoreflect.EnumType {
	return &file_blog_v1_auth_proto_enumTypes[1]
}

func (x WechatLoginStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WechatLoginStatus.Descriptor instead.
func (WechatLoginStatus) EnumDescriptor() ([]byte, []int) {
	return file_blog_v1_auth_proto_rawDescGZIP(), []int{1}
}

// UpdatePasswordRequest is the input for AuthService.UpdatePassword. Both
// fields ride in the request body; the target account comes from the access
// token, never from the payload.
type UpdatePasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current password, verified before the change.
	OldPassword string `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	// New password; at least 8 characters, same rule as account creation.
	NewPassword   string `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_blog_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *UpdatePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *UpdatePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// User is the public representation of an account. Credentials never appear
// in responses.
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application-generated UUID identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Lowercased login email.
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// Human-readable name shown on the site.
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Account role.
	Role UserRole `protobuf:"varint,4,opt,name=role,proto3,enum=blog.v1.UserRole" json:"role,omitempty"`
	// Time at which the account was created. Server-assigned.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Site-relative avatar path, e.g. /v1/assets/avatars/<random>.<ext>, or
	// empty when no avatar was uploaded. Clients resolve it against the API
	// origin (the Nuxt BFF prefixes /api).
	AvatarUrl     string `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_blog_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_blog_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_USER_ROLE_UNSPECIFIED
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

// RegisterRequest is the input for AuthService.Register. The new account is
// always a READER; ADMIN accounts exist only through the seed command.
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Login email, matched case-insensitively and stored lowercased.
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Plaintext password; at least 8 characters. Sent once over TLS.
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// Public display name, 1-32 characters.
	DisplayName   string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_blog_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// LoginRequest is the input for AuthService.Login.
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Login email, matched case-insensitively.
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Plaintext password. Sent once over TLS; never stored in clear text.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_blog_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LoginReply is the output of Login and Refresh. The refresh token itself is
// delivered as an httpOnly cookie and is deliberately not part of the body.
type LoginReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signed access token for the Authorization: Bearer header.
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// Fixed to "Bearer".
	TokenType string `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	// Seconds until access_token expires. Clients should refresh proactively
	// before this elapses.
	ExpiresIn int64 `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	// The authenticated account.
	User          *User `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_blog_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_blog_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *LoginReply) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginReply) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *LoginReply) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *LoginReply) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// RefreshRequest is the input for AuthService.Refresh. The refresh token is
// transported out of band (cookie or X-Refresh-Token header), so the message
// body is empty.
type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_blog_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_auth_proto_rawDescGZIP(), []int{5}
}

// LogoutRequest is the input for AuthService.Logout. Like Refresh, the
// refresh token arrives via cookie or header.
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_blog_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_auth_proto_rawDescGZIP(), []int{6}
}

// GetMeRequest is the input for AuthService.GetMe. The caller is identified
// by the access token, not by any request field.
type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_blog_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_auth_proto_rawDescGZIP(), []int{7}
}

// WechatLoginRequest is the input for AuthService.WechatLogin.
type WechatLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Temporary login code from wx.login in the mini program. Single-use and
	// short-lived on WeChat's side; the server exchanges it immediately.
	Code          string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WechatLoginRequest) Reset() {
	*x = WechatLoginRequest{}
	mi := &file_blog_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WechatLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatLoginRequest) ProtoMessage() {}

func (x *WechatLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatLoginRequest.ProtoReflect.Descriptor instead.
func (*WechatLoginRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *WechatLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// WechatLoginReply is the output of AuthService.WechatLogin. Exactly one of
// `login` or `binding_ticket` is meaningful, selected by `status`.
type WechatLoginReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which follow-up the client should take.
	Status WechatLoginStatus `protobuf:"varint,1,opt,name=status,proto3,enum=blog.v1.WechatLoginStatus" json:"status,omitempty"`
	// Token pair for the bound account; set only when status is OK. The
	// refresh token travels as the standard cookie / X-Refresh-Token.
	Login *LoginReply `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	// Single-use, 10-minute ticket identifying the unbound openid; set only
	// when status is BINDING_REQUIRED. Pass it to BindWechat.
	BindingTicket string `protobuf:"bytes,3,opt,name=binding_ticket,json=bindingTicket,proto3" json:"binding_ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WechatLoginReply) Reset() {
	*x = WechatLoginReply{}
	mi := &file_blog_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WechatLoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatLoginReply) ProtoMessage() {}

func (x *WechatLoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatLoginReply.ProtoReflect.Descriptor instead.
func (*WechatLoginReply) Descriptor() ([]byte, []int) {
	return file_blog_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *WechatLoginReply) GetStatus() WechatLoginStatus {
	if x != nil {
		return x.Status
	}
	return WechatLoginStatus_WECHAT_LOGIN_STATUS_UNSPECIFIED
}

func (x *WechatLoginReply) GetLogin() *LoginReply {
	if x != nil {
		return x.Login
	}
	return nil
}

func (x *WechatLoginReply) GetBindingTicket() string {
	if x != nil {
		return x.BindingTicket
	}
	return ""
}

// BindWechatRequest is the input for AuthService.BindWechat.
type BindWechatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ticket from a WechatLogin reply with status BINDING_REQUIRED. Single
	// use; consumed even when the bind itself fails.
	BindingTicket string `protobuf:"bytes,1,opt,name=binding_ticket,json=bindingTicket,proto3" json:"binding_ticket,omitempty"`
	// Login email of the existing account to attach the openid to.
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// Password of that account; verified before binding.
	Password      string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindWechatRequest) Reset() {
	*x = BindWechatRequest{}
	mi := &file_blog_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindWechatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindWechatRequest) ProtoMessage() {}

func (x *BindWechatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindWechatRequest.ProtoReflect.Descriptor instead.
func (*BindWechatRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *BindWechatRequest) GetBindingTicket() string {
	if x != nil {
		return x.BindingTicket
	}
	return ""
}

func (x *BindWechatRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BindWechatRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_blog_v1_auth_proto protoreflect.FileDescriptor

const file_blog_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12blog/v1/auth.proto\x12\ablog.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n" +
	"\x15UpdatePasswordRequest\x12&\n" +
	"\fold_password\x18\x01 \x01(\tB\x03\xe0A\x02R\voldPassword\x12&\n" +
	"\fnew_password\x18\x02 \x01(\tB\x03\xe0A\x02R\vnewPassword\"\xd0\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12%\n" +
	"\x04role\x18\x04 \x01(\x0e2\x11.blog.v1.UserRoleR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tR\tavatarUrl\"u\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\x05email\x18\x01 \x01(\tB\x03\xe0A\x02R\x05email\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tB\x03\xe0A\x02R\bpassword\x12&\n" +
	"\fdisplay_name\x18\x03 \x01(\tB\x03\xe0A\x02R\vdisplayName\"J\n" +
	"\fLoginRequest\x12\x19\n" +
	"\x05email\x18\x01 \x01(\tB\x03\xe0A\x02R\x05email\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tB\x03\xe0A\x02R\bpassword\"\x90\x01\n" +
	"\n" +
	"LoginReply\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x12!\n" +
	"\x04user\x18\x04 \x01(\v2\r.blog.v1.UserR\x04user\"\x10\n" +
	"\x0eRefreshRequest\"\x0f\n" +
	"\rLogoutRequest\"\x0e\n" +
	"\fGetMeRequest\"-\n" +
	"\x12WechatLoginRequest\x12\x17\n" +
	"\x04code\x18\x01 \x01(\tB\x03\xe0A\x02R\x04code\"\x98\x01\n" +
	"\x10WechatLoginReply\x122\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.blog.v1.WechatLoginStatusR\x06status\x12)\n" +
	"\x05login\x18\x02 \x01(\v2\x13.blog.v1.LoginReplyR\x05login\x12%\n" +
	"\x0ebinding_ticket\x18\x03 \x01(\tR\rbindingTicket\"{\n" +
	"\x11BindWechatRequest\x12*\n" +
	"\x0ebinding_ticket\x18\x01 \x01(\tB\x03\xe0A\x02R\rbindingTicket\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tB\x03\xe0A\x02R\x05email\x12\x1f\n" +
	"\bpassword\x18\x03 \x01(\tB\x03\xe0A\x02R\bpassword*P\n" +
	"\bUserRole\x12\x19\n" +
	"\x15USER_ROLE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fUSER_ROLE_ADMIN\x10\x01\x12\x14\n" +
	"\x10USER_ROLE_READER\x10\x02*~\n" +
	"\x11WechatLoginStatus\x12#\n" +
	"\x1fWECHAT_LOGIN_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16WECHAT_LOGIN_STATUS_OK\x10\x01\x12(\n" +
	"$WECHAT_LOGIN_STATUS_BINDING_REQUIRED\x10\x022\xd8\x05\n" +
	"\vAuthService\x12W\n" +
	"\bRegister\x12\x18.blog.v1.RegisterRequest\x1a\x13.blog.v1.LoginReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/auth/register\x12N\n" +
	"\x05Login\x12\x15.blog.v1.LoginRequest\x1a\x13.blog.v1.LoginReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12T\n" +
	"\aRefresh\x12\x17.blog.v1.RefreshRequest\x1a\x13.blog.v1.LoginReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/auth/refresh\x12T\n" +
	"\x06Logout\x12\x16.blog.v1.LogoutRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/auth/logout\x12B\n" +
	"\x05GetMe\x12\x15.blog.v1.GetMeRequest\x1a\r.blog.v1.User\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/auth/me\x12m\n" +
	"\x0eUpdatePassword\x12\x1e.blog.v1.UpdatePasswordRequest\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/auth/update-password\x12a\n" +
	"\vWechatLogin\x12\x1b.blog.v1.WechatLoginRequest\x1a\x19.blog.v1.WechatLoginReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/auth/wechat\x12^\n" +
	"\n" +
	"BindWechat\x12\x1a.blog.v1.BindWechatRequest\x1a\x13.blog.v1.LoginReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/auth/wechat/bindBa\n" +
	"\x18io.grpc.examples.blog.v1B\tAuthProtoP\x01Z8github.com/luohao0308/luohao-blog/backend/api/blog/v1;v1b\x06proto3"

var (
	file_blog_v1_auth_proto_rawDescOnce sync.Once
	file_blog_v1_auth_proto_rawDescData []byte
)

func file_blog_v1_auth_proto_rawDescGZIP() []byte {
	file_blog_v1_auth_proto_rawDescOnce.Do(func() {
		file_blog_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_v1_auth_proto_rawDesc), len(file_blog_v1_auth_proto_rawDesc)))
	})
	return file_blog_v1_auth_proto_rawDescData
}

var file_blog_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_blog_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_blog_v1_auth_proto_goTypes = []any{
	(UserRole)(0),                 // 0: blog.v1.UserRole
	(WechatLoginStatus)(0),        // 1: blog.v1.WechatLoginStatus
	(*UpdatePasswordRequest)(nil), // 2: blog.v1.UpdatePasswordRequest
	(*User)(nil),                  // 3: blog.v1.User
	(*RegisterRequest)(nil),       // 4: blog.v1.RegisterRequest
	(*LoginRequest)(nil),          // 5: blog.v1.LoginRequest
	(*LoginReply)(nil),            // 6: blog.v1.LoginReply
	(*RefreshRequest)(nil),        // 7: blog.v1.RefreshRequest
	(*LogoutRequest)(nil),         // 8: blog.v1.LogoutRequest
	(*GetMeRequest)(nil),          // 9: blog.v1.GetMeRequest
	(*WechatLoginRequest)(nil),    // 10: blog.v1.WechatLoginRequest
	(*WechatLoginReply)(nil),      // 11: blog.v1.WechatLoginReply
	(*BindWechatRequest)(nil),     // 12: blog.v1.BindWechatRequest
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 14: google.protobuf.Empty
}
var file_blog_v1_auth_proto_depIdxs = []int32{
	0,  // 0: blog.v1.User.role:type_name -> blog.v1.UserRole
	13, // 1: blog.v1.User.created_at:type_name -> google.protobuf.Timestamp
	3,  // 2: blog.v1.LoginReply.user:type_name -> blog.v1.User
	1,  // 3: blog.v1.WechatLoginReply.status:type_name -> blog.v1.WechatLoginStatus
	6,  // 4: blog.v1.WechatLoginReply.login:type_name -> blog.v1.LoginReply
	4,  // 5: blog.v1.AuthService.Register:input_type -> blog.v1.RegisterRequest
	5,  // 6: blog.v1.AuthService.Login:input_type -> blog.v1.LoginRequest
	7,  // 7: blog.v1.AuthService.Refresh:input_type -> blog.v1.RefreshRequest
	8,  // 8: blog.v1.AuthService.Logout:input_type -> blog.v1.LogoutRequest
	9,  // 9: blog.v1.AuthService.GetMe:input_type -> blog.v1.GetMeRequest
	2,  // 10: blog.v1.AuthService.UpdatePassword:input_type -> blog.v1.UpdatePasswordRequest
	10, // 11: blog.v1.AuthService.WechatLogin:input_type -> blog.v1.WechatLoginRequest
	12, // 12: blog.v1.AuthService.BindWechat:input_type -> blog.v1.BindWechatRequest
	6,  // 13: blog.v1.AuthService.Register:output_type -> blog.v1.LoginReply
	6,  // 14: blog.v1.AuthService.Login:output_type -> blog.v1.LoginReply
	6,  // 15: blog.v1.AuthService.Refresh:output_type -> blog.v1.LoginReply
	14, // 16: blog.v1.AuthService.Logout:output_type -> google.protobuf.Empty
	3,  // 17: blog.v1.AuthService.GetMe:output_type -> blog.v1.User
	14, // 18: blog.v1.AuthService.UpdatePassword:output_type -> google.protobuf.Empty
	11, // 19: blog.v1.AuthService.WechatLogin:output_type -> blog.v1.WechatLoginReply
	6,  // 20: blog.v1.AuthService.BindWechat:output_type -> blog.v1.LoginReply
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_blog_v1_auth_proto_init() }
func file_blog_v1_auth_proto_init() {
	if File_blog_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_v1_auth_proto_rawDesc), len(file_blog_v1_auth_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_v1_auth_proto_goTypes,
		DependencyIndexes: file_blog_v1_auth_proto_depIdxs,
		EnumInfos:         file_blog_v1_auth_proto_enumTypes,
		MessageInfos:      file_blog_v1_auth_proto_msgTypes,
	}.Build()
	File_blog_v1_auth_proto = out.File
	file_blog_v1_auth_proto_goTypes = nil
	file_blog_v1_auth_proto_depIdxs = nil
}
