// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: blog/v1/chat.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChatRequest is the input for ChatService.Chat.
type ChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The visitor's question, answered from published article content.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Optional. How many articles to retrieve as context (1-8). Defaults to 4.
	TopK          int32 `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_blog_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ChatRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

// ChatReply is the retrieval-augmented answer.
type ChatReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The generated answer. Plain text, not Markdown.
	Answer string `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	// The published articles the answer drew from, best-match first.
	Citations     []*CitedArticle `protobuf:"bytes,2,rep,name=citations,proto3" json:"citations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatReply) Reset() {
	*x = ChatReply{}
	mi := &file_blog_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReply) ProtoMessage() {}

func (x *ChatReply) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReply.ProtoReflect.Descriptor instead.
func (*ChatReply) Descriptor() ([]byte, []int) {
	return file_blog_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChatReply) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *ChatReply) GetCitations() []*CitedArticle {
	if x != nil {
		return x.Citations
	}
	return nil
}

// CitedArticle identifies one source article of the answer.
type CitedArticle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CitedArticle) Reset() {
	*x = CitedArticle{}
	mi := &file_blog_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CitedArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CitedArticle) ProtoMessage() {}

func (x *CitedArticle) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CitedArticle.ProtoReflect.Descriptor instead.
func (*CitedArticle) Descriptor() ([]byte, []int) {
	return file_blog_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *CitedArticle) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CitedArticle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CitedArticle) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

var File_blog_v1_chat_proto protoreflect.FileDescriptor

const file_blog_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x12blog/v1/chat.proto\x12\ablog.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"=\n" +
	"\vChatRequest\x12\x19\n" +
	"\x05query\x18\x01 \x01(\tB\x03\xe0A\x02R\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\"X\n" +
	"\tChatReply\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x123\n" +
	"\tcitations\x18\x02 \x03(\v2\x15.blog.v1.CitedArticleR\tcitations\"R\n" +
	"\fCitedArticle\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary2T\n" +
	"\vChatService\x12E\n" +
	"\x04Chat\x12\x14.blog.v1.ChatRequest\x1a\x12.blog.v1.ChatReply\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/chatBa\n" +
	"\x18io.grpc.examples.blog.v1B\tChatProtoP\x01Z8github.com/luohao0308/luohao-blog/backend/api/blog/v1;v1b\x06proto3"

var (
	file_blog_v1_chat_proto_rawDescOnce sync.Once
	file_blog_v1_chat_proto_rawDescData []byte
)

func file_blog_v1_chat_proto_rawDescGZIP() []byte {
	file_blog_v1_chat_proto_rawDescOnce.Do(func() {
		file_blog_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_v1_chat_proto_rawDesc), len(file_blog_v1_chat_proto_rawDesc)))
	})
	return file_blog_v1_chat_proto_rawDescData
}

var file_blog_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_blog_v1_chat_proto_goTypes = []any{
	(*ChatRequest)(nil),  // 0: blog.v1.ChatRequest
	(*ChatReply)(nil),    // 1: blog.v1.ChatReply
	(*CitedArticle)(nil), // 2: blog.v1.CitedArticle
}
var file_blog_v1_chat_proto_depIdxs = []int32{
	2, // 0: blog.v1.ChatReply.citations:type_name -> blog.v1.CitedArticle
	0, // 1: blog.v1.ChatService.Chat:input_type -> blog.v1.ChatRequest
	1, // 2: blog.v1.ChatService.Chat:output_type -> blog.v1.ChatReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_blog_v1_chat_proto_init() }
func file_blog_v1_chat_proto_init() {
	if File_blog_v1_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_v1_chat_proto_rawDesc), len(file_blog_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_v1_chat_proto_goTypes,
		DependencyIndexes: file_blog_v1_chat_proto_depIdxs,
		MessageInfos:      file_blog_v1_chat_proto_msgTypes,
	}.Build()
	File_blog_v1_chat_proto = out.File
	file_blog_v1_chat_proto_goTypes = nil
	file_blog_v1_chat_proto_depIdxs = nil
}
