// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: blog/v1/comment.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommentService_CreateComment_FullMethodName       = "/blog.v1.CommentService/CreateComment"
	CommentService_ListArticleComments_FullMethodName = "/blog.v1.CommentService/ListArticleComments"
	CommentService_ListComments_FullMethodName        = "/blog.v1.CommentService/ListComments"
	CommentService_ApproveComment_FullMethodName      = "/blog.v1.CommentService/ApproveComment"
	CommentService_DeleteComment_FullMethodName       = "/blog.v1.CommentService/DeleteComment"
)

// CommentServiceClient is the client API for CommentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CommentService handles visitor comments on articles. Commenters are
// anonymous (registration is closed): every new comment starts PENDING and
// becomes publicly visible only after an admin approves it. Admin operations
// require the Authorization header; public ones are rate limited per client
// IP.
type CommentServiceClient interface {
	// CreateComment submits a visitor comment. The comment enters PENDING and
	// is not publicly visible until approved. The target article must exist
	// and be PUBLISHED. Authorization: public (rate limited per client IP;
	// excess attempts return TOO_MANY_REQUESTS). Returns INVALID_ARGUMENT when
	// fields fail validation and NOT_FOUND when the article is missing or not
	// published.
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*Comment, error)
	// ListArticleComments returns a page of APPROVED comments for an article,
	// newest first. Authorization: public.
	ListArticleComments(ctx context.Context, in *ListArticleCommentsRequest, opts ...grpc.CallOption) (*CommentSet, error)
	// ListComments returns a page of comments in any moderation state, for the
	// admin panel. Use the standard list filter; supported field: `status` as
	// an int literal (1 = PENDING, 2 = APPROVED), e.g. `status = 1`.
	// Authorization: ADMIN only.
	ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*CommentSet, error)
	// ApproveComment moves a comment to APPROVED, making it publicly visible.
	// Idempotent for already-approved comments. Authorization: ADMIN only.
	// Returns NOT_FOUND when the comment does not exist.
	ApproveComment(ctx context.Context, in *ApproveCommentRequest, opts ...grpc.CallOption) (*Comment, error)
	// DeleteComment removes a comment permanently. Pending and approved
	// comments can both be deleted. Authorization: ADMIN only. Returns
	// NOT_FOUND when the comment does not exist.
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type commentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentServiceClient(cc grpc.ClientConnInterface) CommentServiceClient {
	return &commentServiceClient{cc}
}

func (c *commentServiceClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*Comment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Comment)
	err := c.cc.Invoke(ctx, CommentService_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) ListArticleComments(ctx context.Context, in *ListArticleCommentsRequest, opts ...grpc.CallOption) (*CommentSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentSet)
	err := c.cc.Invoke(ctx, CommentService_ListArticleComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*CommentSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentSet)
	err := c.cc.Invoke(ctx, CommentService_ListComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) ApproveComment(ctx context.Context, in *ApproveCommentRequest, opts ...grpc.CallOption) (*Comment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Comment)
	err := c.cc.Invoke(ctx, CommentService_ApproveComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CommentService_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentServiceServer is the server API for CommentService service.
// All implementations must embed UnimplementedCommentServiceServer
// for forward compatibility.
//
// CommentService handles visitor comments on articles. Commenters are
// anonymous (registration is closed): every new comment starts PENDING and
// becomes publicly visible only after an admin approves it. Admin operations
// require the Authorization header; public ones are rate limited per client
// IP.
type CommentServiceServer interface {
	// CreateComment submits a visitor comment. The comment enters PENDING and
	// is not publicly visible until approved. The target article must exist
	// and be PUBLISHED. Authorization: public (rate limited per client IP;
	// excess attempts return TOO_MANY_REQUESTS). Returns INVALID_ARGUMENT when
	// fields fail validation and NOT_FOUND when the article is missing or not
	// published.
	CreateComment(context.Context, *CreateCommentRequest) (*Comment, error)
	// ListArticleComments returns a page of APPROVED comments for an article,
	// newest first. Authorization: public.
	ListArticleComments(context.Context, *ListArticleCommentsRequest) (*CommentSet, error)
	// ListComments returns a page of comments in any moderation state, for the
	// admin panel. Use the standard list filter; supported field: `status` as
	// an int literal (1 = PENDING, 2 = APPROVED), e.g. `status = 1`.
	// Authorization: ADMIN only.
	ListComments(context.Context, *ListCommentsRequest) (*CommentSet, error)
	// ApproveComment moves a comment to APPROVED, making it publicly visible.
	// Idempotent for already-approved comments. Authorization: ADMIN only.
	// Returns NOT_FOUND when the comment does not exist.
	ApproveComment(context.Context, *ApproveCommentRequest) (*Comment, error)
	// DeleteComment removes a comment permanently. Pending and approved
	// comments can both be deleted. Authorization: ADMIN only. Returns
	// NOT_FOUND when the comment does not exist.
	DeleteComment(context.Context, *DeleteCommentRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedCommentServiceServer()
}

// UnimplementedCommentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommentServiceServer struct{}

func (UnimplementedCommentServiceServer) CreateComment(context.Context, *CreateCommentRequest) (*Comment, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedCommentServiceServer) ListArticleComments(context.Context, *ListArticleCommentsRequest) (*CommentSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListArticleComments not implemented")
}
func (UnimplementedCommentServiceServer) ListComments(context.Context, *ListCommentsRequest) (*CommentSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComments not implemented")
}
func (UnimplementedCommentServiceServer) ApproveComment(context.Context, *ApproveCommentRequest) (*Comment, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveComment not implemented")
}
func (UnimplementedCommentServiceServer) DeleteComment(context.Context, *DeleteCommentRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedCommentServiceServer) mustEmbedUnimplementedCommentServiceServer() {}
func (UnimplementedCommentServiceServer) testEmbeddedByValue()                        {}

// UnsafeCommentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentServiceServer will
// result in compilation errors.
type UnsafeCommentServiceServer interface {
	mustEmbedUnimplementedCommentServiceServer()
}

func RegisterCommentServiceServer(s grpc.ServiceRegistrar, srv CommentServiceServer) {
	// If the following call panics, it indicates UnimplementedCommentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommentService_ServiceDesc, srv)
}

func _CommentService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentService_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_ListArticleComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArticleCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).ListArticleComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentService_ListArticleComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).ListArticleComments(ctx, req.(*ListArticleCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentService_ListComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).ListComments(ctx, req.(*ListCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_ApproveComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).ApproveComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentService_ApproveComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).ApproveComment(ctx, req.(*ApproveCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).DeleteComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommentService_ServiceDesc is the grpc.ServiceDesc for CommentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blog.v1.CommentService",
	HandlerType: (*CommentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateComment",
			Handler:    _CommentService_CreateComment_Handler,
		},
		{
			MethodName: "ListArticleComments",
			Handler:    _CommentService_ListArticleComments_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _CommentService_ListComments_Handler,
		},
		{
			MethodName: "ApproveComment",
			Handler:    _CommentService_ApproveComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _CommentService_DeleteComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog/v1/comment.proto",
}
