// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: blog/v1/comment.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommentStatus is the moderation state of a comment.
type CommentStatus int32

const (
	// Default value. Never returned by the server.
	CommentStatus_COMMENT_STATUS_UNSPECIFIED CommentStatus = 0
	// The comment awaits moderation and is not publicly visible.
	CommentStatus_COMMENT_STATUS_PENDING CommentStatus = 1
	// The comment was approved by an admin and is publicly visible.
	CommentStatus_COMMENT_STATUS_APPROVED CommentStatus = 2
)

// Enum value maps for CommentStatus.
var (
	CommentStatus_name = map[int32]string{
		0: "COMMENT_STATUS_UNSPECIFIED",
		1: "COMMENT_STATUS_PENDING",
		2: "COMMENT_STATUS_APPROVED",
	}
	CommentStatus_value = map[string]int32{
		"COMMENT_STATUS_UNSPECIFIED": 0,
		"COMMENT_STATUS_PENDING":     1,
		"COMMENT_STATUS_APPROVED":    2,
	}
)

func (x CommentStatus) Enum() *CommentStatus {
	p := new(CommentStatus)
	*p = x
	return p
}

func (x CommentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_blog_v1_comment_proto_enumTypes[0].Descriptor()
}

func (CommentStatus) Type() protoreflect.EnumType {
	return &file_blog_v1_comment_proto_enumTypes[0]
}

func (x CommentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommentStatus.Descriptor instead.
func (CommentStatus) EnumDescriptor() ([]byte, []int) {
	return file_blog_v1_comment_proto_rawDescGZIP(), []int{0}
}

// Comment is the canonical representation of a visitor comment.
type Comment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application-generated UUIDv7 identifier. Read-only.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Slug of the commented article.
	ArticleSlug string `protobuf:"bytes,2,opt,name=article_slug,json=articleSlug,proto3" json:"article_slug,omitempty"`
	// Visitor-provided display name.
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Visitor-provided comment body.
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// Moderation state. Server-assigned: new comments start PENDING.
	Status CommentStatus `protobuf:"varint,5,opt,name=status,proto3,enum=blog.v1.CommentStatus" json:"status,omitempty"`
	// Time at which the comment was created. Server-assigned, read-only.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Time at which the comment was last modified. Server-assigned, read-only.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_blog_v1_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_blog_v1_comment_proto_rawDescGZIP(), []int{0}
}

func (x *Comment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Comment) GetArticleSlug() string {
	if x != nil {
		return x.ArticleSlug
	}
	return ""
}

func (x *Comment) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetStatus() CommentStatus {
	if x != nil {
		return x.Status
	}
	return CommentStatus_COMMENT_STATUS_UNSPECIFIED
}

func (x *Comment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Comment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CommentSet is a paginated collection of comments.
type CommentSet struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Comments []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	// Token used to retrieve the next page. Empty when there are no more
	// results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentSet) Reset() {
	*x = CommentSet{}
	mi := &file_blog_v1_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentSet) ProtoMessage() {}

func (x *CommentSet) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentSet.ProtoReflect.Descriptor instead.
func (*CommentSet) Descriptor() ([]byte, []int) {
	return file_blog_v1_comment_proto_rawDescGZIP(), []int{1}
}

func (x *CommentSet) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *CommentSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// CreateCommentRequest is the input for CommentService.CreateComment.
type CreateCommentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Slug of the article being commented on. Must reference a PUBLISHED
	// article.
	ArticleSlug string `protobuf:"bytes,1,opt,name=article_slug,json=articleSlug,proto3" json:"article_slug,omitempty"`
	// Visitor display name, 1-32 characters.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Comment body, 1-1000 characters.
	Content       string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_blog_v1_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_comment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCommentRequest) GetArticleSlug() string {
	if x != nil {
		return x.ArticleSlug
	}
	return ""
}

func (x *CreateCommentRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ListArticleCommentsRequest is the input for
// CommentService.ListArticleComments.
type ListArticleCommentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Slug of the article whose approved comments are listed.
	Slug string `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	// Optional. Maximum number of comments to return in a single page.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. Token from a previous response's next_page_token.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticleCommentsRequest) Reset() {
	*x = ListArticleCommentsRequest{}
	mi := &file_blog_v1_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticleCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticleCommentsRequest) ProtoMessage() {}

func (x *ListArticleCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticleCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListArticleCommentsRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_comment_proto_rawDescGZIP(), []int{3}
}

func (x *ListArticleCommentsRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ListArticleCommentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListArticleCommentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListCommentsRequest is the input for CommentService.ListComments.
type ListCommentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Maximum number of comments to return in a single page.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. Token from a previous response's next_page_token.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. The standard list filter. Supported field: `status` as an int
	// literal (1 = PENDING, 2 = APPROVED), e.g. `status = 1`.
	Filter        string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsRequest) Reset() {
	*x = ListCommentsRequest{}
	mi := &file_blog_v1_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsRequest) ProtoMessage() {}

func (x *ListCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_comment_proto_rawDescGZIP(), []int{4}
}

func (x *ListCommentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCommentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListCommentsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// ApproveCommentRequest is the input for CommentService.ApproveComment.
type ApproveCommentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the comment to approve.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveCommentRequest) Reset() {
	*x = ApproveCommentRequest{}
	mi := &file_blog_v1_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveCommentRequest) ProtoMessage() {}

func (x *ApproveCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveCommentRequest.ProtoReflect.Descriptor instead.
func (*ApproveCommentRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_comment_proto_rawDescGZIP(), []int{5}
}

func (x *ApproveCommentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteCommentRequest is the input for CommentService.DeleteComment.
type DeleteCommentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the comment to delete.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_blog_v1_comment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_comment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_comment_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCommentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_blog_v1_comment_proto protoreflect.FileDescriptor

const file_blog_v1_comment_proto_rawDesc = "" +
	"\n" +
	"\x15blog/v1/comment.proto\x12\ablog.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x02\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\farticle_slug\x18\x02 \x01(\tR\varticleSlug\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12.\n" +
	"\x06status\x18\x05 \x01(\x0e2\x16.blog.v1.CommentStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"b\n" +
	"\n" +
	"CommentSet\x12,\n" +
	"\bcomments\x18\x01 \x03(\v2\x10.blog.v1.CommentR\bcomments\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x85\x01\n" +
	"\x14CreateCommentRequest\x12&\n" +
	"\farticle_slug\x18\x01 \x01(\tB\x03\xe0A\x02R\varticleSlug\x12&\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\x03\xe0A\x02R\vdisplayName\x12\x1d\n" +
	"\acontent\x18\x03 \x01(\tB\x03\xe0A\x02R\acontent\"q\n" +
	"\x1aListArticleCommentsRequest\x12\x17\n" +
	"\x04slug\x18\x01 \x01(\tB\x03\xe0A\x02R\x04slug\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"i\n" +
	"\x13ListCommentsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\",\n" +
	"\x15ApproveCommentRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"+\n" +
	"\x14DeleteCommentRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id*h\n" +
	"\rCommentStatus\x12\x1e\n" +
	"\x1aCOMMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16COMMENT_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17COMMENT_STATUS_APPROVED\x10\x022\x88\x04\n" +
	"\x0eCommentService\x12Y\n" +
	"\rCreateComment\x12\x1d.blog.v1.CreateCommentRequest\x1a\x10.blog.v1.Comment\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/comments\x12u\n" +
	"\x13ListArticleComments\x12#.blog.v1.ListArticleCommentsRequest\x1a\x13.blog.v1.CommentSet\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/articles/{slug}/comments\x12W\n" +
	"\fListComments\x12\x1c.blog.v1.ListCommentsRequest\x1a\x13.blog.v1.CommentSet\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/comments\x12h\n" +
	"\x0eApproveComment\x12\x1e.blog.v1.ApproveCommentRequest\x1a\x10.blog.v1.Comment\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/comments/{id}/approve\x12a\n" +
	"\rDeleteComment\x12\x1d.blog.v1.DeleteCommentRequest\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/comments/{id}Bd\n" +
	"\x18io.grpc.examples.blog.v1B\fCommentProtoP\x01Z8github.com/luohao0308/luohao-blog/backend/api/blog/v1;v1b\x06proto3"

var (
	file_blog_v1_comment_proto_rawDescOnce sync.Once
	file_blog_v1_comment_proto_rawDescData []byte
)

func file_blog_v1_comment_proto_rawDescGZIP() []byte {
	file_blog_v1_comment_proto_rawDescOnce.Do(func() {
		file_blog_v1_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_v1_comment_proto_rawDesc), len(file_blog_v1_comment_proto_rawDesc)))
	})
	return file_blog_v1_comment_proto_rawDescData
}

var file_blog_v1_comment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blog_v1_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_blog_v1_comment_proto_goTypes = []any{
	(CommentStatus)(0),                 // 0: blog.v1.CommentStatus
	(*Comment)(nil),                    // 1: blog.v1.Comment
	(*CommentSet)(nil),                 // 2: blog.v1.CommentSet
	(*CreateCommentRequest)(nil),       // 3: blog.v1.CreateCommentRequest
	(*ListArticleCommentsRequest)(nil), // 4: blog.v1.ListArticleCommentsRequest
	(*ListCommentsRequest)(nil),        // 5: blog.v1.ListCommentsRequest
	(*ApproveCommentRequest)(nil),      // 6: blog.v1.ApproveCommentRequest
	(*DeleteCommentRequest)(nil),       // 7: blog.v1.DeleteCommentRequest
	(*timestamppb.Timestamp)(nil),      // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 9: google.protobuf.Empty
}
var file_blog_v1_comment_proto_depIdxs = []int32{
	0, // 0: blog.v1.Comment.status:type_name -> blog.v1.CommentStatus
	8, // 1: blog.v1.Comment.created_at:type_name -> google.protobuf.Timestamp
	8, // 2: blog.v1.Comment.updated_at:type_name -> google.protobuf.Timestamp
	1, // 3: blog.v1.CommentSet.comments:type_name -> blog.v1.Comment
	3, // 4: blog.v1.CommentService.CreateComment:input_type -> blog.v1.CreateCommentRequest
	4, // 5: blog.v1.CommentService.ListArticleComments:input_type -> blog.v1.ListArticleCommentsRequest
	5, // 6: blog.v1.CommentService.ListComments:input_type -> blog.v1.ListCommentsRequest
	6, // 7: blog.v1.CommentService.ApproveComment:input_type -> blog.v1.ApproveCommentRequest
	7, // 8: blog.v1.CommentService.DeleteComment:input_type -> blog.v1.DeleteCommentRequest
	1, // 9: blog.v1.CommentService.CreateComment:output_type -> blog.v1.Comment
	2, // 10: blog.v1.CommentService.ListArticleComments:output_type -> blog.v1.CommentSet
	2, // 11: blog.v1.CommentService.ListComments:output_type -> blog.v1.CommentSet
	1, // 12: blog.v1.CommentService.ApproveComment:output_type -> blog.v1.Comment
	9, // 13: blog.v1.CommentService.DeleteComment:output_type -> google.protobuf.Empty
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_blog_v1_comment_proto_init() }
func file_blog_v1_comment_proto_init() {
	if File_blog_v1_comment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_v1_comment_proto_rawDesc), len(file_blog_v1_comment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_v1_comment_proto_goTypes,
		DependencyIndexes: file_blog_v1_comment_proto_depIdxs,
		EnumInfos:         file_blog_v1_comment_proto_enumTypes,
		MessageInfos:      file_blog_v1_comment_proto_msgTypes,
	}.Build()
	File_blog_v1_comment_proto = out.File
	file_blog_v1_comment_proto_goTypes = nil
	file_blog_v1_comment_proto_depIdxs = nil
}
