// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: blog/v1/comment.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationCommentServiceApproveComment = "/blog.v1.CommentService/ApproveComment"
const OperationCommentServiceCreateComment = "/blog.v1.CommentService/CreateComment"
const OperationCommentServiceDeleteComment = "/blog.v1.CommentService/DeleteComment"
const OperationCommentServiceListArticleComments = "/blog.v1.CommentService/ListArticleComments"
const OperationCommentServiceListComments = "/blog.v1.CommentService/ListComments"

type CommentServiceHTTPServer interface {
	// ApproveComment ApproveComment moves a comment to APPROVED, making it publicly visible.
	// Idempotent for already-approved comments. Authorization: ADMIN only.
	// Returns NOT_FOUND when the comment does not exist.
	ApproveComment(context.Context, *ApproveCommentRequest) (*Comment, error)
	// CreateComment CreateComment submits a comment authored by the calling account. The
	// comment enters PENDING and is not publicly visible until approved. The
	// target article must exist and be PUBLISHED. The display name is the
	// account's current profile name; the payload carries no identity fields.
	// Authorization: any authenticated account (Authorization: Bearer);
	// anonymous calls return UNAUTHORIZED. Rate limited per client IP; excess
	// attempts return TOO_MANY_REQUESTS. Returns INVALID_ARGUMENT when fields
	// fail validation and NOT_FOUND when the article is missing or not
	// published.
	CreateComment(context.Context, *CreateCommentRequest) (*Comment, error)
	// DeleteComment DeleteComment removes a comment permanently. Pending and approved
	// comments can both be deleted. Authorization: ADMIN only. Returns
	// NOT_FOUND when the comment does not exist.
	DeleteComment(context.Context, *DeleteCommentRequest) (*emptypb.Empty, error)
	// ListArticleComments ListArticleComments returns a page of APPROVED comments for an article,
	// newest first. Authorization: public.
	ListArticleComments(context.Context, *ListArticleCommentsRequest) (*CommentSet, error)
	// ListComments ListComments returns a page of comments in any moderation state, for the
	// admin panel. Use the standard list filter; supported field: `status` as
	// an int literal (1 = PENDING, 2 = APPROVED), e.g. `status = 1`.
	// Authorization: ADMIN only.
	ListComments(context.Context, *ListCommentsRequest) (*CommentSet, error)
}

func RegisterCommentServiceHTTPServer(s *http.Server, srv CommentServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/comments", _CommentService_CreateComment0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/articles/{slug}/comments", _CommentService_ListArticleComments0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/comments", _CommentService_ListComments0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/comments/{id}/approve", _CommentService_ApproveComment0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/comments/{id}", _CommentService_DeleteComment0_HTTP_Handler(srv))
}

func _CommentService_CreateComment0_HTTP_Handler(srv CommentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCommentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommentServiceCreateComment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateComment(ctx, req.(*CreateCommentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Comment)
		return ctx.Result(200, reply)
	}
}

func _CommentService_ListArticleComments0_HTTP_Handler(srv CommentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListArticleCommentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommentServiceListArticleComments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListArticleComments(ctx, req.(*ListArticleCommentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CommentSet)
		return ctx.Result(200, reply)
	}
}

func _CommentService_ListComments0_HTTP_Handler(srv CommentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCommentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommentServiceListComments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListComments(ctx, req.(*ListCommentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CommentSet)
		return ctx.Result(200, reply)
	}
}

func _CommentService_ApproveComment0_HTTP_Handler(srv CommentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ApproveCommentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommentServiceApproveComment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ApproveComment(ctx, req.(*ApproveCommentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Comment)
		return ctx.Result(200, reply)
	}
}

func _CommentService_DeleteComment0_HTTP_Handler(srv CommentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteCommentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommentServiceDeleteComment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteComment(ctx, req.(*DeleteCommentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type CommentServiceHTTPClient interface {
	// ApproveComment ApproveComment moves a comment to APPROVED, making it publicly visible.
	// Idempotent for already-approved comments. Authorization: ADMIN only.
	// Returns NOT_FOUND when the comment does not exist.
	ApproveComment(ctx context.Context, req *ApproveCommentRequest, opts ...http.CallOption) (rsp *Comment, err error)
	// CreateComment CreateComment submits a comment authored by the calling account. The
	// comment enters PENDING and is not publicly visible until approved. The
	// target article must exist and be PUBLISHED. The display name is the
	// account's current profile name; the payload carries no identity fields.
	// Authorization: any authenticated account (Authorization: Bearer);
	// anonymous calls return UNAUTHORIZED. Rate limited per client IP; excess
	// attempts return TOO_MANY_REQUESTS. Returns INVALID_ARGUMENT when fields
	// fail validation and NOT_FOUND when the article is missing or not
	// published.
	CreateComment(ctx context.Context, req *CreateCommentRequest, opts ...http.CallOption) (rsp *Comment, err error)
	// DeleteComment DeleteComment removes a comment permanently. Pending and approved
	// comments can both be deleted. Authorization: ADMIN only. Returns
	// NOT_FOUND when the comment does not exist.
	DeleteComment(ctx context.Context, req *DeleteCommentRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// ListArticleComments ListArticleComments returns a page of APPROVED comments for an article,
	// newest first. Authorization: public.
	ListArticleComments(ctx context.Context, req *ListArticleCommentsRequest, opts ...http.CallOption) (rsp *CommentSet, err error)
	// ListComments ListComments returns a page of comments in any moderation state, for the
	// admin panel. Use the standard list filter; supported field: `status` as
	// an int literal (1 = PENDING, 2 = APPROVED), e.g. `status = 1`.
	// Authorization: ADMIN only.
	ListComments(ctx context.Context, req *ListCommentsRequest, opts ...http.CallOption) (rsp *CommentSet, err error)
}

type CommentServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCommentServiceHTTPClient(client *http.Client) CommentServiceHTTPClient {
	return &CommentServiceHTTPClientImpl{client}
}

// ApproveComment ApproveComment moves a comment to APPROVED, making it publicly visible.
// Idempotent for already-approved comments. Authorization: ADMIN only.
// Returns NOT_FOUND when the comment does not exist.
func (c *CommentServiceHTTPClientImpl) ApproveComment(ctx context.Context, in *ApproveCommentRequest, opts ...http.CallOption) (*Comment, error) {
	var out Comment
	pattern := "/v1/comments/{id}/approve"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCommentServiceApproveComment),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateComment CreateComment submits a comment authored by the calling account. The
// comment enters PENDING and is not publicly visible until approved. The
// target article must exist and be PUBLISHED. The display name is the
// account's current profile name; the payload carries no identity fields.
// Authorization: any authenticated account (Authorization: Bearer);
// anonymous calls return UNAUTHORIZED. Rate limited per client IP; excess
// attempts return TOO_MANY_REQUESTS. Returns INVALID_ARGUMENT when fields
// fail validation and NOT_FOUND when the article is missing or not
// published.
func (c *CommentServiceHTTPClientImpl) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...http.CallOption) (*Comment, error) {
	var out Comment
	pattern := "/v1/comments"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCommentServiceCreateComment),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteComment DeleteComment removes a comment permanently. Pending and approved
// comments can both be deleted. Authorization: ADMIN only. Returns
// NOT_FOUND when the comment does not exist.
func (c *CommentServiceHTTPClientImpl) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/comments/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCommentServiceDeleteComment),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListArticleComments ListArticleComments returns a page of APPROVED comments for an article,
// newest first. Authorization: public.
func (c *CommentServiceHTTPClientImpl) ListArticleComments(ctx context.Context, in *ListArticleCommentsRequest, opts ...http.CallOption) (*CommentSet, error) {
	var out CommentSet
	pattern := "/v1/articles/{slug}/comments"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCommentServiceListArticleComments),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListComments ListComments returns a page of comments in any moderation state, for the
// admin panel. Use the standard list filter; supported field: `status` as
// an int literal (1 = PENDING, 2 = APPROVED), e.g. `status = 1`.
// Authorization: ADMIN only.
func (c *CommentServiceHTTPClientImpl) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...http.CallOption) (*CommentSet, error) {
	var out CommentSet
	pattern := "/v1/comments"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCommentServiceListComments),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
