// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: blog/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_ARTICLE_UNSPECIFIED        ErrorReason = 0
	ErrorReason_ARTICLE_NOT_FOUND          ErrorReason = 1
	ErrorReason_ARTICLE_INVALID_ARGUMENT   ErrorReason = 2
	ErrorReason_ARTICLE_SLUG_CONFLICT      ErrorReason = 3
	ErrorReason_USER_NOT_FOUND             ErrorReason = 4
	ErrorReason_USER_INVALID_ARGUMENT      ErrorReason = 5
	ErrorReason_USER_INVALID_CREDENTIALS   ErrorReason = 6
	ErrorReason_USER_EMAIL_CONFLICT        ErrorReason = 7
	ErrorReason_AUTH_UNAUTHORIZED          ErrorReason = 8
	ErrorReason_AUTH_TOKEN_EXPIRED         ErrorReason = 9
	ErrorReason_AUTH_INVALID_REFRESH_TOKEN ErrorReason = 10
	ErrorReason_AUTH_TOO_MANY_ATTEMPTS     ErrorReason = 11
	ErrorReason_AUTH_FORBIDDEN             ErrorReason = 12
	ErrorReason_COMMENT_NOT_FOUND          ErrorReason = 13
	ErrorReason_COMMENT_INVALID_ARGUMENT   ErrorReason = 14
	ErrorReason_COMMENT_TOO_MANY_ATTEMPTS  ErrorReason = 15
	ErrorReason_CHAT_UNAVAILABLE           ErrorReason = 16
	ErrorReason_CHAT_INVALID_ARGUMENT      ErrorReason = 17
	ErrorReason_CHAT_TOO_MANY_ATTEMPTS     ErrorReason = 18
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:  "ARTICLE_UNSPECIFIED",
		1:  "ARTICLE_NOT_FOUND",
		2:  "ARTICLE_INVALID_ARGUMENT",
		3:  "ARTICLE_SLUG_CONFLICT",
		4:  "USER_NOT_FOUND",
		5:  "USER_INVALID_ARGUMENT",
		6:  "USER_INVALID_CREDENTIALS",
		7:  "USER_EMAIL_CONFLICT",
		8:  "AUTH_UNAUTHORIZED",
		9:  "AUTH_TOKEN_EXPIRED",
		10: "AUTH_INVALID_REFRESH_TOKEN",
		11: "AUTH_TOO_MANY_ATTEMPTS",
		12: "AUTH_FORBIDDEN",
		13: "COMMENT_NOT_FOUND",
		14: "COMMENT_INVALID_ARGUMENT",
		15: "COMMENT_TOO_MANY_ATTEMPTS",
		16: "CHAT_UNAVAILABLE",
		17: "CHAT_INVALID_ARGUMENT",
		18: "CHAT_TOO_MANY_ATTEMPTS",
	}
	ErrorReason_value = map[string]int32{
		"ARTICLE_UNSPECIFIED":        0,
		"ARTICLE_NOT_FOUND":          1,
		"ARTICLE_INVALID_ARGUMENT":   2,
		"ARTICLE_SLUG_CONFLICT":      3,
		"USER_NOT_FOUND":             4,
		"USER_INVALID_ARGUMENT":      5,
		"USER_INVALID_CREDENTIALS":   6,
		"USER_EMAIL_CONFLICT":        7,
		"AUTH_UNAUTHORIZED":          8,
		"AUTH_TOKEN_EXPIRED":         9,
		"AUTH_INVALID_REFRESH_TOKEN": 10,
		"AUTH_TOO_MANY_ATTEMPTS":     11,
		"AUTH_FORBIDDEN":             12,
		"COMMENT_NOT_FOUND":          13,
		"COMMENT_INVALID_ARGUMENT":   14,
		"COMMENT_TOO_MANY_ATTEMPTS":  15,
		"CHAT_UNAVAILABLE":           16,
		"CHAT_INVALID_ARGUMENT":      17,
		"CHAT_TOO_MANY_ATTEMPTS":     18,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_blog_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_blog_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_blog_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_blog_v1_error_reason_proto protoreflect.FileDescriptor

const file_blog_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1ablog/v1/error_reason.proto\x12\ablog.v1*\xfc\x03\n" +
	"\vErrorReason\x12\x17\n" +
	"\x13ARTICLE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ARTICLE_NOT_FOUND\x10\x01\x12\x1c\n" +
	"\x18ARTICLE_INVALID_ARGUMENT\x10\x02\x12\x19\n" +
	"\x15ARTICLE_SLUG_CONFLICT\x10\x03\x12\x12\n" +
	"\x0eUSER_NOT_FOUND\x10\x04\x12\x19\n" +
	"\x15USER_INVALID_ARGUMENT\x10\x05\x12\x1c\n" +
	"\x18USER_INVALID_CREDENTIALS\x10\x06\x12\x17\n" +
	"\x13USER_EMAIL_CONFLICT\x10\a\x12\x15\n" +
	"\x11AUTH_UNAUTHORIZED\x10\b\x12\x16\n" +
	"\x12AUTH_TOKEN_EXPIRED\x10\t\x12\x1e\n" +
	"\x1aAUTH_INVALID_REFRESH_TOKEN\x10\n" +
	"\x12\x1a\n" +
	"\x16AUTH_TOO_MANY_ATTEMPTS\x10\v\x12\x12\n" +
	"\x0eAUTH_FORBIDDEN\x10\f\x12\x15\n" +
	"\x11COMMENT_NOT_FOUND\x10\r\x12\x1c\n" +
	"\x18COMMENT_INVALID_ARGUMENT\x10\x0e\x12\x1d\n" +
	"\x19COMMENT_TOO_MANY_ATTEMPTS\x10\x0f\x12\x14\n" +
	"\x10CHAT_UNAVAILABLE\x10\x10\x12\x19\n" +
	"\x15CHAT_INVALID_ARGUMENT\x10\x11\x12\x1a\n" +
	"\x16CHAT_TOO_MANY_ATTEMPTS\x10\x12BQ\n" +
	"\ablog.v1P\x01Z8github.com/luohao0308/luohao-blog/backend/api/blog/v1;v1\xa2\x02\tAPIBlogV1b\x06proto3"

var (
	file_blog_v1_error_reason_proto_rawDescOnce sync.Once
	file_blog_v1_error_reason_proto_rawDescData []byte
)

func file_blog_v1_error_reason_proto_rawDescGZIP() []byte {
	file_blog_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_blog_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_v1_error_reason_proto_rawDesc), len(file_blog_v1_error_reason_proto_rawDesc)))
	})
	return file_blog_v1_error_reason_proto_rawDescData
}

var file_blog_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blog_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: blog.v1.ErrorReason
}
var file_blog_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blog_v1_error_reason_proto_init() }
func file_blog_v1_error_reason_proto_init() {
	if File_blog_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_v1_error_reason_proto_rawDesc), len(file_blog_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blog_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_blog_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_blog_v1_error_reason_proto_enumTypes,
	}.Build()
	File_blog_v1_error_reason_proto = out.File
	file_blog_v1_error_reason_proto_goTypes = nil
	file_blog_v1_error_reason_proto_depIdxs = nil
}
