// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: blog/v1/search.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SearchArticlesRequest is the input for ArticleSearchService.SearchArticles.
type SearchArticlesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Free-text query. Matched against title (boosted), summary, content, and
	// tags of published articles.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Optional. Maximum number of articles to return in a single page.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. Token from a previous response's next_page_token.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchArticlesRequest) Reset() {
	*x = SearchArticlesRequest{}
	mi := &file_blog_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchArticlesRequest) ProtoMessage() {}

func (x *SearchArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchArticlesRequest.ProtoReflect.Descriptor instead.
func (*SearchArticlesRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchArticlesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchArticlesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchArticlesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

var File_blog_v1_search_proto protoreflect.FileDescriptor

const file_blog_v1_search_proto_rawDesc = "" +
	"\n" +
	"\x14blog/v1/search.proto\x12\ablog.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x15blog/v1/article.proto\x1a\x1fgoogle/api/field_behavior.proto\"n\n" +
	"\x15SearchArticlesRequest\x12\x19\n" +
	"\x05query\x18\x01 \x01(\tB\x03\xe0A\x02R\x05query\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken2z\n" +
	"\x14ArticleSearchService\x12b\n" +
	"\x0eSearchArticles\x12\x1e.blog.v1.SearchArticlesRequest\x1a\x13.blog.v1.ArticleSet\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/search/articlesBc\n" +
	"\x18io.grpc.examples.blog.v1B\vSearchProtoP\x01Z8github.com/luohao0308/luohao-blog/backend/api/blog/v1;v1b\x06proto3"

var (
	file_blog_v1_search_proto_rawDescOnce sync.Once
	file_blog_v1_search_proto_rawDescData []byte
)

func file_blog_v1_search_proto_rawDescGZIP() []byte {
	file_blog_v1_search_proto_rawDescOnce.Do(func() {
		file_blog_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_v1_search_proto_rawDesc), len(file_blog_v1_search_proto_rawDesc)))
	})
	return file_blog_v1_search_proto_rawDescData
}

var file_blog_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blog_v1_search_proto_goTypes = []any{
	(*SearchArticlesRequest)(nil), // 0: blog.v1.SearchArticlesRequest
	(*ArticleSet)(nil),            // 1: blog.v1.ArticleSet
}
var file_blog_v1_search_proto_depIdxs = []int32{
	0, // 0: blog.v1.ArticleSearchService.SearchArticles:input_type -> blog.v1.SearchArticlesRequest
	1, // 1: blog.v1.ArticleSearchService.SearchArticles:output_type -> blog.v1.ArticleSet
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blog_v1_search_proto_init() }
func file_blog_v1_search_proto_init() {
	if File_blog_v1_search_proto != nil {
		return
	}
	file_blog_v1_article_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_v1_search_proto_rawDesc), len(file_blog_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_v1_search_proto_goTypes,
		DependencyIndexes: file_blog_v1_search_proto_depIdxs,
		MessageInfos:      file_blog_v1_search_proto_msgTypes,
	}.Build()
	File_blog_v1_search_proto = out.File
	file_blog_v1_search_proto_goTypes = nil
	file_blog_v1_search_proto_depIdxs = nil
}
