// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: blog/v1/search.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationArticleSearchServiceSearchArticles = "/blog.v1.ArticleSearchService/SearchArticles"

type ArticleSearchServiceHTTPServer interface {
	// SearchArticles SearchArticles full-text searches published articles (BM25, Chinese
	// analyzed) and returns them best-match first. Only PUBLISHED articles are
	// indexed and returned. Authorization: public.
	// Returns INVALID_ARGUMENT when the query is empty.
	SearchArticles(context.Context, *SearchArticlesRequest) (*ArticleSet, error)
}

func RegisterArticleSearchServiceHTTPServer(s *http.Server, srv ArticleSearchServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/search/articles", _ArticleSearchService_SearchArticles0_HTTP_Handler(srv))
}

func _ArticleSearchService_SearchArticles0_HTTP_Handler(srv ArticleSearchServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchArticlesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleSearchServiceSearchArticles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchArticles(ctx, req.(*SearchArticlesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ArticleSet)
		return ctx.Result(200, reply)
	}
}

type ArticleSearchServiceHTTPClient interface {
	// SearchArticles SearchArticles full-text searches published articles (BM25, Chinese
	// analyzed) and returns them best-match first. Only PUBLISHED articles are
	// indexed and returned. Authorization: public.
	// Returns INVALID_ARGUMENT when the query is empty.
	SearchArticles(ctx context.Context, req *SearchArticlesRequest, opts ...http.CallOption) (rsp *ArticleSet, err error)
}

type ArticleSearchServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewArticleSearchServiceHTTPClient(client *http.Client) ArticleSearchServiceHTTPClient {
	return &ArticleSearchServiceHTTPClientImpl{client}
}

// SearchArticles SearchArticles full-text searches published articles (BM25, Chinese
// analyzed) and returns them best-match first. Only PUBLISHED articles are
// indexed and returned. Authorization: public.
// Returns INVALID_ARGUMENT when the query is empty.
func (c *ArticleSearchServiceHTTPClientImpl) SearchArticles(ctx context.Context, in *SearchArticlesRequest, opts ...http.CallOption) (*ArticleSet, error) {
	var out ArticleSet
	pattern := "/v1/search/articles"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationArticleSearchServiceSearchArticles),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
