// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: blog/v1/subscriber.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubscriberService_Subscribe_FullMethodName        = "/blog.v1.SubscriberService/Subscribe"
	SubscriberService_ListSubscribers_FullMethodName  = "/blog.v1.SubscriberService/ListSubscribers"
	SubscriberService_DeleteSubscriber_FullMethodName = "/blog.v1.SubscriberService/DeleteSubscriber"
)

// SubscriberServiceClient is the client API for SubscriberService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SubscriberService registers emails for future article notifications. Actual
// sending is not wired yet: subscribing records the email so a future sender
// can pick the list up. Subscribe is idempotent — re-subscribing an existing
// email succeeds without change, so the public endpoint does not leak which
// addresses are registered.
type SubscriberServiceClient interface {
	// Subscribe registers an email address. Emails are stored lowercased.
	// Authorization: public (rate limited per client IP).
	// Returns INVALID_ARGUMENT if the email is malformed, and TOO_MANY_ATTEMPTS
	// when the client exceeds the submission budget.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListSubscribers returns a page of subscribers ordered by creation time,
	// newest first. Authorization: ADMIN only (Authorization: Bearer).
	ListSubscribers(ctx context.Context, in *ListSubscribersRequest, opts ...grpc.CallOption) (*SubscriberSet, error)
	// DeleteSubscriber removes a subscription.
	// Authorization: ADMIN only (Authorization: Bearer).
	// Returns NOT_FOUND if no subscriber exists with the supplied email.
	DeleteSubscriber(ctx context.Context, in *DeleteSubscriberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type subscriberServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriberServiceClient(cc grpc.ClientConnInterface) SubscriberServiceClient {
	return &subscriberServiceClient{cc}
}

func (c *subscriberServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SubscriberService_Subscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriberServiceClient) ListSubscribers(ctx context.Context, in *ListSubscribersRequest, opts ...grpc.CallOption) (*SubscriberSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriberSet)
	err := c.cc.Invoke(ctx, SubscriberService_ListSubscribers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriberServiceClient) DeleteSubscriber(ctx context.Context, in *DeleteSubscriberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SubscriberService_DeleteSubscriber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriberServiceServer is the server API for SubscriberService service.
// All implementations must embed UnimplementedSubscriberServiceServer
// for forward compatibility.
//
// SubscriberService registers emails for future article notifications. Actual
// sending is not wired yet: subscribing records the email so a future sender
// can pick the list up. Subscribe is idempotent — re-subscribing an existing
// email succeeds without change, so the public endpoint does not leak which
// addresses are registered.
type SubscriberServiceServer interface {
	// Subscribe registers an email address. Emails are stored lowercased.
	// Authorization: public (rate limited per client IP).
	// Returns INVALID_ARGUMENT if the email is malformed, and TOO_MANY_ATTEMPTS
	// when the client exceeds the submission budget.
	Subscribe(context.Context, *SubscribeRequest) (*emptypb.Empty, error)
	// ListSubscribers returns a page of subscribers ordered by creation time,
	// newest first. Authorization: ADMIN only (Authorization: Bearer).
	ListSubscribers(context.Context, *ListSubscribersRequest) (*SubscriberSet, error)
	// DeleteSubscriber removes a subscription.
	// Authorization: ADMIN only (Authorization: Bearer).
	// Returns NOT_FOUND if no subscriber exists with the supplied email.
	DeleteSubscriber(context.Context, *DeleteSubscriberRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSubscriberServiceServer()
}

// UnimplementedSubscriberServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscriberServiceServer struct{}

func (UnimplementedSubscriberServiceServer) Subscribe(context.Context, *SubscribeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedSubscriberServiceServer) ListSubscribers(context.Context, *ListSubscribersRequest) (*SubscriberSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSubscribers not implemented")
}
func (UnimplementedSubscriberServiceServer) DeleteSubscriber(context.Context, *DeleteSubscriberRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSubscriber not implemented")
}
func (UnimplementedSubscriberServiceServer) mustEmbedUnimplementedSubscriberServiceServer() {}
func (UnimplementedSubscriberServiceServer) testEmbeddedByValue()                           {}

// UnsafeSubscriberServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriberServiceServer will
// result in compilation errors.
type UnsafeSubscriberServiceServer interface {
	mustEmbedUnimplementedSubscriberServiceServer()
}

func RegisterSubscriberServiceServer(s grpc.ServiceRegistrar, srv SubscriberServiceServer) {
	// If the following call panics, it indicates UnimplementedSubscriberServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubscriberService_ServiceDesc, srv)
}

func _SubscriberService_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriberServiceServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriberService_Subscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriberServiceServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriberService_ListSubscribers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubscribersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriberServiceServer).ListSubscribers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriberService_ListSubscribers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriberServiceServer).ListSubscribers(ctx, req.(*ListSubscribersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriberService_DeleteSubscriber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSubscriberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriberServiceServer).DeleteSubscriber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriberService_DeleteSubscriber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriberServiceServer).DeleteSubscriber(ctx, req.(*DeleteSubscriberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubscriberService_ServiceDesc is the grpc.ServiceDesc for SubscriberService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriberService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blog.v1.SubscriberService",
	HandlerType: (*SubscriberServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _SubscriberService_Subscribe_Handler,
		},
		{
			MethodName: "ListSubscribers",
			Handler:    _SubscriberService_ListSubscribers_Handler,
		},
		{
			MethodName: "DeleteSubscriber",
			Handler:    _SubscriberService_DeleteSubscriber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog/v1/subscriber.proto",
}
