// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: blog/v1/user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UpdateProfileRequest is the input for UserService.UpdateProfile. The
// target account comes from the access token, never from the payload.
type UpdateProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New public display name, 1-32 characters after trimming.
	DisplayName   string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_blog_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateProfileRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// UploadAvatarRequest is the input for UserService.UploadAvatar. The target
// account comes from the access token, never from the payload.
type UploadAvatarRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw image bytes (jpeg/png/webp), at most 2 MiB after the transport
	// decodes the base64 JSON encoding.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAvatarRequest) Reset() {
	*x = UploadAvatarRequest{}
	mi := &file_blog_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarRequest) ProtoMessage() {}

func (x *UploadAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarRequest.ProtoReflect.Descriptor instead.
func (*UploadAvatarRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UploadAvatarRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// GetAvatarRequest is the input for UserService.GetAvatar.
type GetAvatarRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-generated filename as embedded in User.avatar_url.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvatarRequest) Reset() {
	*x = GetAvatarRequest{}
	mi := &file_blog_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvatarRequest) ProtoMessage() {}

func (x *GetAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvatarRequest.ProtoReflect.Descriptor instead.
func (*GetAvatarRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetAvatarRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_blog_v1_user_proto protoreflect.FileDescriptor

const file_blog_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12blog/v1/user.proto\x12\ablog.v1\x1a\x12blog/v1/auth.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/httpbody.proto\">\n" +
	"\x14UpdateProfileRequest\x12&\n" +
	"\fdisplay_name\x18\x01 \x01(\tB\x03\xe0A\x02R\vdisplayName\".\n" +
	"\x13UploadAvatarRequest\x12\x17\n" +
	"\x04data\x18\x01 \x01(\fB\x03\xe0A\x02R\x04data\"+\n" +
	"\x10GetAvatarRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name2\xa3\x02\n" +
	"\vUserService\x12Z\n" +
	"\rUpdateProfile\x12\x1d.blog.v1.UpdateProfileRequest\x1a\r.blog.v1.User\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/v1/user/profile\x12W\n" +
	"\fUploadAvatar\x12\x1c.blog.v1.UploadAvatarRequest\x1a\r.blog.v1.User\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\x1a\x0f/v1/user/avatar\x12_\n" +
	"\tGetAvatar\x12\x19.blog.v1.GetAvatarRequest\x1a\x14.google.api.HttpBody\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/assets/avatars/{name}Ba\n" +
	"\x18io.grpc.examples.blog.v1B\tUserProtoP\x01Z8github.com/luohao0308/luohao-blog/backend/api/blog/v1;v1b\x06proto3"

var (
	file_blog_v1_user_proto_rawDescOnce sync.Once
	file_blog_v1_user_proto_rawDescData []byte
)

func file_blog_v1_user_proto_rawDescGZIP() []byte {
	file_blog_v1_user_proto_rawDescOnce.Do(func() {
		file_blog_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_v1_user_proto_rawDesc), len(file_blog_v1_user_proto_rawDesc)))
	})
	return file_blog_v1_user_proto_rawDescData
}

var file_blog_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_blog_v1_user_proto_goTypes = []any{
	(*UpdateProfileRequest)(nil), // 0: blog.v1.UpdateProfileRequest
	(*UploadAvatarRequest)(nil),  // 1: blog.v1.UploadAvatarRequest
	(*GetAvatarRequest)(nil),     // 2: blog.v1.GetAvatarRequest
	(*User)(nil),                 // 3: blog.v1.User
	(*httpbody.HttpBody)(nil),    // 4: google.api.HttpBody
}
var file_blog_v1_user_proto_depIdxs = []int32{
	0, // 0: blog.v1.UserService.UpdateProfile:input_type -> blog.v1.UpdateProfileRequest
	1, // 1: blog.v1.UserService.UploadAvatar:input_type -> blog.v1.UploadAvatarRequest
	2, // 2: blog.v1.UserService.GetAvatar:input_type -> blog.v1.GetAvatarRequest
	3, // 3: blog.v1.UserService.UpdateProfile:output_type -> blog.v1.User
	3, // 4: blog.v1.UserService.UploadAvatar:output_type -> blog.v1.User
	4, // 5: blog.v1.UserService.GetAvatar:output_type -> google.api.HttpBody
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blog_v1_user_proto_init() }
func file_blog_v1_user_proto_init() {
	if File_blog_v1_user_proto != nil {
		return
	}
	file_blog_v1_auth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_v1_user_proto_rawDesc), len(file_blog_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_v1_user_proto_goTypes,
		DependencyIndexes: file_blog_v1_user_proto_depIdxs,
		MessageInfos:      file_blog_v1_user_proto_msgTypes,
	}.Build()
	File_blog_v1_user_proto = out.File
	file_blog_v1_user_proto_goTypes = nil
	file_blog_v1_user_proto_depIdxs = nil
}
